package com.dao;

import com.entity.EcsAreaRegion;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsAreaRegionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_area_region
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("shipping_area_id") Short shipping_area_id, @Param("region_id") Short region_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_area_region
     *
     * @mbg.generated
     */
    int insert(EcsAreaRegion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_area_region
     *
     * @mbg.generated
     */
    List<EcsAreaRegion> selectAll();
}