package com.dao;

import com.entity.EcsCard;
import java.util.List;

public interface EcsCardMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Byte card_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbg.generated
     */
    int insert(EcsCard record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbg.generated
     */
    EcsCard selectByPrimaryKey(Byte card_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbg.generated
     */
    List<EcsCard> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_card
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsCard record);
}