package com.dao;

import com.entity.EcsDeliveryGoods;
import java.util.List;

public interface EcsDeliveryGoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_delivery_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer rec_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_delivery_goods
     *
     * @mbg.generated
     */
    int insert(EcsDeliveryGoods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_delivery_goods
     *
     * @mbg.generated
     */
    EcsDeliveryGoods selectByPrimaryKey(Integer rec_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_delivery_goods
     *
     * @mbg.generated
     */
    List<EcsDeliveryGoods> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_delivery_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsDeliveryGoods record);
}