package com.dao;

import com.entity.EcsGoodsCat;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EcsGoodsCatMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_cat
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("goods_id") Integer goods_id, @Param("cat_id") Short cat_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_cat
     *
     * @mbg.generated
     */
    int insert(EcsGoodsCat record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_goods_cat
     *
     * @mbg.generated
     */
    List<EcsGoodsCat> selectAll();
}