package com.dao;

import com.entity.EcsTakegoodsType;
import java.util.List;

public interface EcsTakegoodsTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short type_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type
     *
     * @mbg.generated
     */
    int insert(EcsTakegoodsType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type
     *
     * @mbg.generated
     */
    EcsTakegoodsType selectByPrimaryKey(Short type_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type
     *
     * @mbg.generated
     */
    List<EcsTakegoodsType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_takegoods_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EcsTakegoodsType record);
}