package com.dao;

import com.entity.EventsStatementsHistogramByDigest;
import java.util.List;

public interface EventsStatementsHistogramByDigestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_histogram_by_digest
     *
     * @mbg.generated
     */
    int insert(EventsStatementsHistogramByDigest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_statements_histogram_by_digest
     *
     * @mbg.generated
     */
    List<EventsStatementsHistogramByDigest> selectAll();
}