package com.dao;

import com.entity.EventsTransactionsHistory;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface EventsTransactionsHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_history
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(@Param("THREAD_ID") Long THREAD_ID, @Param("EVENT_ID") Long EVENT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_history
     *
     * @mbg.generated
     */
    int insert(EventsTransactionsHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_history
     *
     * @mbg.generated
     */
    EventsTransactionsHistory selectByPrimaryKey(@Param("THREAD_ID") Long THREAD_ID, @Param("EVENT_ID") Long EVENT_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_history
     *
     * @mbg.generated
     */
    List<EventsTransactionsHistory> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_transactions_history
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EventsTransactionsHistory record);
}