package com.dao;

import com.entity.EventsErrorsSummaryByUserByError;
import java.util.List;

public interface EventsErrorsSummaryByUserByErrorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_errors_summary_by_user_by_error
     *
     * @mbg.generated
     */
    int insert(EventsErrorsSummaryByUserByError record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table events_errors_summary_by_user_by_error
     *
     * @mbg.generated
     */
    List<EventsErrorsSummaryByUserByError> selectAll();
}