package com.dao;

import com.entity.FileInstances;
import java.util.List;

public interface FileInstancesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String FILE_NAME);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated
     */
    int insert(FileInstances record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated
     */
    FileInstances selectByPrimaryKey(String FILE_NAME);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated
     */
    List<FileInstances> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file_instances
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FileInstances record);
}