package com.dao;

import com.entity.FilmList;
import java.util.List;

public interface FilmListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_list
     *
     * @mbg.generated
     */
    int insert(FilmList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_list
     *
     * @mbg.generated
     */
    List<FilmList> selectAll();
}