package com.dao;

import com.entity.FilmText;
import java.util.List;

public interface FilmTextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Short film_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbg.generated
     */
    int insert(FilmText record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbg.generated
     */
    FilmText selectByPrimaryKey(Short film_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbg.generated
     */
    List<FilmText> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table film_text
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FilmText record);
}