package com.dao;

import com.entity.GlobalStatus;
import java.util.List;

public interface GlobalStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String VARIABLE_NAME);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated
     */
    int insert(GlobalStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated
     */
    GlobalStatus selectByPrimaryKey(String VARIABLE_NAME);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated
     */
    List<GlobalStatus> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table global_status
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GlobalStatus record);
}