package com.dao;

import com.entity.InnodbTablespaces;
import java.util.List;

public interface InnodbTablespacesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TABLESPACES
     *
     * @mbg.generated
     */
    int insert(InnodbTablespaces record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_TABLESPACES
     *
     * @mbg.generated
     */
    List<InnodbTablespaces> selectAll();
}