package com.dao;

import com.entity.OptimizerTrace;
import java.util.List;

public interface OptimizerTraceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated
     */
    int insert(OptimizerTrace record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table OPTIMIZER_TRACE
     *
     * @mbg.generated
     */
    List<OptimizerTrace> selectAll();
}