package com.dao;

import com.entity.Threads;
import java.util.List;

public interface ThreadsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long THREAD_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated
     */
    int insert(Threads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated
     */
    Threads selectByPrimaryKey(Long THREAD_ID);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated
     */
    List<Threads> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table threads
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Threads record);
}