package com.dao;

import com.entity.XMemoryGlobalTotal;
import java.util.List;

public interface XMemoryGlobalTotalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$memory_global_total
     *
     * @mbg.generated
     */
    int insert(XMemoryGlobalTotal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table x$memory_global_total
     *
     * @mbg.generated
     */
    List<XMemoryGlobalTotal> selectAll();
}