package com.entity;

import java.math.BigDecimal;

public class EcsGoods {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_id
     *
     * @mbg.generated
     */
    private Integer goods_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.cat_id
     *
     * @mbg.generated
     */
    private Short cat_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_sn
     *
     * @mbg.generated
     */
    private String goods_sn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_name
     *
     * @mbg.generated
     */
    private String goods_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_name_style
     *
     * @mbg.generated
     */
    private String goods_name_style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.click_count
     *
     * @mbg.generated
     */
    private Integer click_count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.brand_id
     *
     * @mbg.generated
     */
    private Short brand_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.provider_name
     *
     * @mbg.generated
     */
    private String provider_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_number
     *
     * @mbg.generated
     */
    private Short goods_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_weight
     *
     * @mbg.generated
     */
    private BigDecimal goods_weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.market_price
     *
     * @mbg.generated
     */
    private BigDecimal market_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.shop_price
     *
     * @mbg.generated
     */
    private BigDecimal shop_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.promote_price
     *
     * @mbg.generated
     */
    private BigDecimal promote_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.promote_start_date
     *
     * @mbg.generated
     */
    private Integer promote_start_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.promote_end_date
     *
     * @mbg.generated
     */
    private Integer promote_end_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_buy
     *
     * @mbg.generated
     */
    private Integer is_buy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.buymax
     *
     * @mbg.generated
     */
    private Integer buymax;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.buymax_start_date
     *
     * @mbg.generated
     */
    private Integer buymax_start_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.buymax_end_date
     *
     * @mbg.generated
     */
    private Integer buymax_end_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.warn_number
     *
     * @mbg.generated
     */
    private Byte warn_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.keywords
     *
     * @mbg.generated
     */
    private String keywords;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_brief
     *
     * @mbg.generated
     */
    private String goods_brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_thumb
     *
     * @mbg.generated
     */
    private String goods_thumb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_img
     *
     * @mbg.generated
     */
    private String goods_img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.original_img
     *
     * @mbg.generated
     */
    private String original_img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_real
     *
     * @mbg.generated
     */
    private Byte is_real;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.extension_code
     *
     * @mbg.generated
     */
    private String extension_code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_on_sale
     *
     * @mbg.generated
     */
    private Boolean is_on_sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_alone_sale
     *
     * @mbg.generated
     */
    private Boolean is_alone_sale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_shipping
     *
     * @mbg.generated
     */
    private Boolean is_shipping;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.integral
     *
     * @mbg.generated
     */
    private Integer integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.add_time
     *
     * @mbg.generated
     */
    private Integer add_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.sort_order
     *
     * @mbg.generated
     */
    private Short sort_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_delete
     *
     * @mbg.generated
     */
    private Boolean is_delete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_best
     *
     * @mbg.generated
     */
    private Boolean is_best;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_new
     *
     * @mbg.generated
     */
    private Boolean is_new;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_hot
     *
     * @mbg.generated
     */
    private Boolean is_hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_promote
     *
     * @mbg.generated
     */
    private Boolean is_promote;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.zhekou
     *
     * @mbg.generated
     */
    private BigDecimal zhekou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.bonus_type_id
     *
     * @mbg.generated
     */
    private Byte bonus_type_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.last_update
     *
     * @mbg.generated
     */
    private Integer last_update;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_type
     *
     * @mbg.generated
     */
    private Short goods_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.seller_note
     *
     * @mbg.generated
     */
    private String seller_note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.give_integral
     *
     * @mbg.generated
     */
    private Integer give_integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.rank_integral
     *
     * @mbg.generated
     */
    private Integer rank_integral;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.suppliers_id
     *
     * @mbg.generated
     */
    private Short suppliers_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.supplier_id
     *
     * @mbg.generated
     */
    private Integer supplier_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.supplier_status
     *
     * @mbg.generated
     */
    private Boolean supplier_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_check
     *
     * @mbg.generated
     */
    private Boolean is_check;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_catindex
     *
     * @mbg.generated
     */
    private Boolean is_catindex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.cost_price
     *
     * @mbg.generated
     */
    private BigDecimal cost_price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.valid_date
     *
     * @mbg.generated
     */
    private Integer valid_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.is_virtual
     *
     * @mbg.generated
     */
    private Integer is_virtual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.zq_source
     *
     * @mbg.generated
     */
    private String zq_source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.zq_id
     *
     * @mbg.generated
     */
    private String zq_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.goods_desc
     *
     * @mbg.generated
     */
    private String goods_desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_goods.supplier_status_txt
     *
     * @mbg.generated
     */
    private String supplier_status_txt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_id
     *
     * @return the value of ecs_goods.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoods_id() {
        return goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_id
     *
     * @param goods_id the value for ecs_goods.goods_id
     *
     * @mbg.generated
     */
    public void setGoods_id(Integer goods_id) {
        this.goods_id = goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.cat_id
     *
     * @return the value of ecs_goods.cat_id
     *
     * @mbg.generated
     */
    public Short getCat_id() {
        return cat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.cat_id
     *
     * @param cat_id the value for ecs_goods.cat_id
     *
     * @mbg.generated
     */
    public void setCat_id(Short cat_id) {
        this.cat_id = cat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_sn
     *
     * @return the value of ecs_goods.goods_sn
     *
     * @mbg.generated
     */
    public String getGoods_sn() {
        return goods_sn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_sn
     *
     * @param goods_sn the value for ecs_goods.goods_sn
     *
     * @mbg.generated
     */
    public void setGoods_sn(String goods_sn) {
        this.goods_sn = goods_sn == null ? null : goods_sn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_name
     *
     * @return the value of ecs_goods.goods_name
     *
     * @mbg.generated
     */
    public String getGoods_name() {
        return goods_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_name
     *
     * @param goods_name the value for ecs_goods.goods_name
     *
     * @mbg.generated
     */
    public void setGoods_name(String goods_name) {
        this.goods_name = goods_name == null ? null : goods_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_name_style
     *
     * @return the value of ecs_goods.goods_name_style
     *
     * @mbg.generated
     */
    public String getGoods_name_style() {
        return goods_name_style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_name_style
     *
     * @param goods_name_style the value for ecs_goods.goods_name_style
     *
     * @mbg.generated
     */
    public void setGoods_name_style(String goods_name_style) {
        this.goods_name_style = goods_name_style == null ? null : goods_name_style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.click_count
     *
     * @return the value of ecs_goods.click_count
     *
     * @mbg.generated
     */
    public Integer getClick_count() {
        return click_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.click_count
     *
     * @param click_count the value for ecs_goods.click_count
     *
     * @mbg.generated
     */
    public void setClick_count(Integer click_count) {
        this.click_count = click_count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.brand_id
     *
     * @return the value of ecs_goods.brand_id
     *
     * @mbg.generated
     */
    public Short getBrand_id() {
        return brand_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.brand_id
     *
     * @param brand_id the value for ecs_goods.brand_id
     *
     * @mbg.generated
     */
    public void setBrand_id(Short brand_id) {
        this.brand_id = brand_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.provider_name
     *
     * @return the value of ecs_goods.provider_name
     *
     * @mbg.generated
     */
    public String getProvider_name() {
        return provider_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.provider_name
     *
     * @param provider_name the value for ecs_goods.provider_name
     *
     * @mbg.generated
     */
    public void setProvider_name(String provider_name) {
        this.provider_name = provider_name == null ? null : provider_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_number
     *
     * @return the value of ecs_goods.goods_number
     *
     * @mbg.generated
     */
    public Short getGoods_number() {
        return goods_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_number
     *
     * @param goods_number the value for ecs_goods.goods_number
     *
     * @mbg.generated
     */
    public void setGoods_number(Short goods_number) {
        this.goods_number = goods_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_weight
     *
     * @return the value of ecs_goods.goods_weight
     *
     * @mbg.generated
     */
    public BigDecimal getGoods_weight() {
        return goods_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_weight
     *
     * @param goods_weight the value for ecs_goods.goods_weight
     *
     * @mbg.generated
     */
    public void setGoods_weight(BigDecimal goods_weight) {
        this.goods_weight = goods_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.market_price
     *
     * @return the value of ecs_goods.market_price
     *
     * @mbg.generated
     */
    public BigDecimal getMarket_price() {
        return market_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.market_price
     *
     * @param market_price the value for ecs_goods.market_price
     *
     * @mbg.generated
     */
    public void setMarket_price(BigDecimal market_price) {
        this.market_price = market_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.shop_price
     *
     * @return the value of ecs_goods.shop_price
     *
     * @mbg.generated
     */
    public BigDecimal getShop_price() {
        return shop_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.shop_price
     *
     * @param shop_price the value for ecs_goods.shop_price
     *
     * @mbg.generated
     */
    public void setShop_price(BigDecimal shop_price) {
        this.shop_price = shop_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.promote_price
     *
     * @return the value of ecs_goods.promote_price
     *
     * @mbg.generated
     */
    public BigDecimal getPromote_price() {
        return promote_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.promote_price
     *
     * @param promote_price the value for ecs_goods.promote_price
     *
     * @mbg.generated
     */
    public void setPromote_price(BigDecimal promote_price) {
        this.promote_price = promote_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.promote_start_date
     *
     * @return the value of ecs_goods.promote_start_date
     *
     * @mbg.generated
     */
    public Integer getPromote_start_date() {
        return promote_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.promote_start_date
     *
     * @param promote_start_date the value for ecs_goods.promote_start_date
     *
     * @mbg.generated
     */
    public void setPromote_start_date(Integer promote_start_date) {
        this.promote_start_date = promote_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.promote_end_date
     *
     * @return the value of ecs_goods.promote_end_date
     *
     * @mbg.generated
     */
    public Integer getPromote_end_date() {
        return promote_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.promote_end_date
     *
     * @param promote_end_date the value for ecs_goods.promote_end_date
     *
     * @mbg.generated
     */
    public void setPromote_end_date(Integer promote_end_date) {
        this.promote_end_date = promote_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_buy
     *
     * @return the value of ecs_goods.is_buy
     *
     * @mbg.generated
     */
    public Integer getIs_buy() {
        return is_buy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_buy
     *
     * @param is_buy the value for ecs_goods.is_buy
     *
     * @mbg.generated
     */
    public void setIs_buy(Integer is_buy) {
        this.is_buy = is_buy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.buymax
     *
     * @return the value of ecs_goods.buymax
     *
     * @mbg.generated
     */
    public Integer getBuymax() {
        return buymax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.buymax
     *
     * @param buymax the value for ecs_goods.buymax
     *
     * @mbg.generated
     */
    public void setBuymax(Integer buymax) {
        this.buymax = buymax;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.buymax_start_date
     *
     * @return the value of ecs_goods.buymax_start_date
     *
     * @mbg.generated
     */
    public Integer getBuymax_start_date() {
        return buymax_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.buymax_start_date
     *
     * @param buymax_start_date the value for ecs_goods.buymax_start_date
     *
     * @mbg.generated
     */
    public void setBuymax_start_date(Integer buymax_start_date) {
        this.buymax_start_date = buymax_start_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.buymax_end_date
     *
     * @return the value of ecs_goods.buymax_end_date
     *
     * @mbg.generated
     */
    public Integer getBuymax_end_date() {
        return buymax_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.buymax_end_date
     *
     * @param buymax_end_date the value for ecs_goods.buymax_end_date
     *
     * @mbg.generated
     */
    public void setBuymax_end_date(Integer buymax_end_date) {
        this.buymax_end_date = buymax_end_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.warn_number
     *
     * @return the value of ecs_goods.warn_number
     *
     * @mbg.generated
     */
    public Byte getWarn_number() {
        return warn_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.warn_number
     *
     * @param warn_number the value for ecs_goods.warn_number
     *
     * @mbg.generated
     */
    public void setWarn_number(Byte warn_number) {
        this.warn_number = warn_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.keywords
     *
     * @return the value of ecs_goods.keywords
     *
     * @mbg.generated
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.keywords
     *
     * @param keywords the value for ecs_goods.keywords
     *
     * @mbg.generated
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_brief
     *
     * @return the value of ecs_goods.goods_brief
     *
     * @mbg.generated
     */
    public String getGoods_brief() {
        return goods_brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_brief
     *
     * @param goods_brief the value for ecs_goods.goods_brief
     *
     * @mbg.generated
     */
    public void setGoods_brief(String goods_brief) {
        this.goods_brief = goods_brief == null ? null : goods_brief.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_thumb
     *
     * @return the value of ecs_goods.goods_thumb
     *
     * @mbg.generated
     */
    public String getGoods_thumb() {
        return goods_thumb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_thumb
     *
     * @param goods_thumb the value for ecs_goods.goods_thumb
     *
     * @mbg.generated
     */
    public void setGoods_thumb(String goods_thumb) {
        this.goods_thumb = goods_thumb == null ? null : goods_thumb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_img
     *
     * @return the value of ecs_goods.goods_img
     *
     * @mbg.generated
     */
    public String getGoods_img() {
        return goods_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_img
     *
     * @param goods_img the value for ecs_goods.goods_img
     *
     * @mbg.generated
     */
    public void setGoods_img(String goods_img) {
        this.goods_img = goods_img == null ? null : goods_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.original_img
     *
     * @return the value of ecs_goods.original_img
     *
     * @mbg.generated
     */
    public String getOriginal_img() {
        return original_img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.original_img
     *
     * @param original_img the value for ecs_goods.original_img
     *
     * @mbg.generated
     */
    public void setOriginal_img(String original_img) {
        this.original_img = original_img == null ? null : original_img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_real
     *
     * @return the value of ecs_goods.is_real
     *
     * @mbg.generated
     */
    public Byte getIs_real() {
        return is_real;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_real
     *
     * @param is_real the value for ecs_goods.is_real
     *
     * @mbg.generated
     */
    public void setIs_real(Byte is_real) {
        this.is_real = is_real;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.extension_code
     *
     * @return the value of ecs_goods.extension_code
     *
     * @mbg.generated
     */
    public String getExtension_code() {
        return extension_code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.extension_code
     *
     * @param extension_code the value for ecs_goods.extension_code
     *
     * @mbg.generated
     */
    public void setExtension_code(String extension_code) {
        this.extension_code = extension_code == null ? null : extension_code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_on_sale
     *
     * @return the value of ecs_goods.is_on_sale
     *
     * @mbg.generated
     */
    public Boolean getIs_on_sale() {
        return is_on_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_on_sale
     *
     * @param is_on_sale the value for ecs_goods.is_on_sale
     *
     * @mbg.generated
     */
    public void setIs_on_sale(Boolean is_on_sale) {
        this.is_on_sale = is_on_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_alone_sale
     *
     * @return the value of ecs_goods.is_alone_sale
     *
     * @mbg.generated
     */
    public Boolean getIs_alone_sale() {
        return is_alone_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_alone_sale
     *
     * @param is_alone_sale the value for ecs_goods.is_alone_sale
     *
     * @mbg.generated
     */
    public void setIs_alone_sale(Boolean is_alone_sale) {
        this.is_alone_sale = is_alone_sale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_shipping
     *
     * @return the value of ecs_goods.is_shipping
     *
     * @mbg.generated
     */
    public Boolean getIs_shipping() {
        return is_shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_shipping
     *
     * @param is_shipping the value for ecs_goods.is_shipping
     *
     * @mbg.generated
     */
    public void setIs_shipping(Boolean is_shipping) {
        this.is_shipping = is_shipping;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.integral
     *
     * @return the value of ecs_goods.integral
     *
     * @mbg.generated
     */
    public Integer getIntegral() {
        return integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.integral
     *
     * @param integral the value for ecs_goods.integral
     *
     * @mbg.generated
     */
    public void setIntegral(Integer integral) {
        this.integral = integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.add_time
     *
     * @return the value of ecs_goods.add_time
     *
     * @mbg.generated
     */
    public Integer getAdd_time() {
        return add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.add_time
     *
     * @param add_time the value for ecs_goods.add_time
     *
     * @mbg.generated
     */
    public void setAdd_time(Integer add_time) {
        this.add_time = add_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.sort_order
     *
     * @return the value of ecs_goods.sort_order
     *
     * @mbg.generated
     */
    public Short getSort_order() {
        return sort_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.sort_order
     *
     * @param sort_order the value for ecs_goods.sort_order
     *
     * @mbg.generated
     */
    public void setSort_order(Short sort_order) {
        this.sort_order = sort_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_delete
     *
     * @return the value of ecs_goods.is_delete
     *
     * @mbg.generated
     */
    public Boolean getIs_delete() {
        return is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_delete
     *
     * @param is_delete the value for ecs_goods.is_delete
     *
     * @mbg.generated
     */
    public void setIs_delete(Boolean is_delete) {
        this.is_delete = is_delete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_best
     *
     * @return the value of ecs_goods.is_best
     *
     * @mbg.generated
     */
    public Boolean getIs_best() {
        return is_best;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_best
     *
     * @param is_best the value for ecs_goods.is_best
     *
     * @mbg.generated
     */
    public void setIs_best(Boolean is_best) {
        this.is_best = is_best;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_new
     *
     * @return the value of ecs_goods.is_new
     *
     * @mbg.generated
     */
    public Boolean getIs_new() {
        return is_new;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_new
     *
     * @param is_new the value for ecs_goods.is_new
     *
     * @mbg.generated
     */
    public void setIs_new(Boolean is_new) {
        this.is_new = is_new;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_hot
     *
     * @return the value of ecs_goods.is_hot
     *
     * @mbg.generated
     */
    public Boolean getIs_hot() {
        return is_hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_hot
     *
     * @param is_hot the value for ecs_goods.is_hot
     *
     * @mbg.generated
     */
    public void setIs_hot(Boolean is_hot) {
        this.is_hot = is_hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_promote
     *
     * @return the value of ecs_goods.is_promote
     *
     * @mbg.generated
     */
    public Boolean getIs_promote() {
        return is_promote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_promote
     *
     * @param is_promote the value for ecs_goods.is_promote
     *
     * @mbg.generated
     */
    public void setIs_promote(Boolean is_promote) {
        this.is_promote = is_promote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.zhekou
     *
     * @return the value of ecs_goods.zhekou
     *
     * @mbg.generated
     */
    public BigDecimal getZhekou() {
        return zhekou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.zhekou
     *
     * @param zhekou the value for ecs_goods.zhekou
     *
     * @mbg.generated
     */
    public void setZhekou(BigDecimal zhekou) {
        this.zhekou = zhekou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.bonus_type_id
     *
     * @return the value of ecs_goods.bonus_type_id
     *
     * @mbg.generated
     */
    public Byte getBonus_type_id() {
        return bonus_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.bonus_type_id
     *
     * @param bonus_type_id the value for ecs_goods.bonus_type_id
     *
     * @mbg.generated
     */
    public void setBonus_type_id(Byte bonus_type_id) {
        this.bonus_type_id = bonus_type_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.last_update
     *
     * @return the value of ecs_goods.last_update
     *
     * @mbg.generated
     */
    public Integer getLast_update() {
        return last_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.last_update
     *
     * @param last_update the value for ecs_goods.last_update
     *
     * @mbg.generated
     */
    public void setLast_update(Integer last_update) {
        this.last_update = last_update;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_type
     *
     * @return the value of ecs_goods.goods_type
     *
     * @mbg.generated
     */
    public Short getGoods_type() {
        return goods_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_type
     *
     * @param goods_type the value for ecs_goods.goods_type
     *
     * @mbg.generated
     */
    public void setGoods_type(Short goods_type) {
        this.goods_type = goods_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.seller_note
     *
     * @return the value of ecs_goods.seller_note
     *
     * @mbg.generated
     */
    public String getSeller_note() {
        return seller_note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.seller_note
     *
     * @param seller_note the value for ecs_goods.seller_note
     *
     * @mbg.generated
     */
    public void setSeller_note(String seller_note) {
        this.seller_note = seller_note == null ? null : seller_note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.give_integral
     *
     * @return the value of ecs_goods.give_integral
     *
     * @mbg.generated
     */
    public Integer getGive_integral() {
        return give_integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.give_integral
     *
     * @param give_integral the value for ecs_goods.give_integral
     *
     * @mbg.generated
     */
    public void setGive_integral(Integer give_integral) {
        this.give_integral = give_integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.rank_integral
     *
     * @return the value of ecs_goods.rank_integral
     *
     * @mbg.generated
     */
    public Integer getRank_integral() {
        return rank_integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.rank_integral
     *
     * @param rank_integral the value for ecs_goods.rank_integral
     *
     * @mbg.generated
     */
    public void setRank_integral(Integer rank_integral) {
        this.rank_integral = rank_integral;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.suppliers_id
     *
     * @return the value of ecs_goods.suppliers_id
     *
     * @mbg.generated
     */
    public Short getSuppliers_id() {
        return suppliers_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.suppliers_id
     *
     * @param suppliers_id the value for ecs_goods.suppliers_id
     *
     * @mbg.generated
     */
    public void setSuppliers_id(Short suppliers_id) {
        this.suppliers_id = suppliers_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.supplier_id
     *
     * @return the value of ecs_goods.supplier_id
     *
     * @mbg.generated
     */
    public Integer getSupplier_id() {
        return supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.supplier_id
     *
     * @param supplier_id the value for ecs_goods.supplier_id
     *
     * @mbg.generated
     */
    public void setSupplier_id(Integer supplier_id) {
        this.supplier_id = supplier_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.supplier_status
     *
     * @return the value of ecs_goods.supplier_status
     *
     * @mbg.generated
     */
    public Boolean getSupplier_status() {
        return supplier_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.supplier_status
     *
     * @param supplier_status the value for ecs_goods.supplier_status
     *
     * @mbg.generated
     */
    public void setSupplier_status(Boolean supplier_status) {
        this.supplier_status = supplier_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_check
     *
     * @return the value of ecs_goods.is_check
     *
     * @mbg.generated
     */
    public Boolean getIs_check() {
        return is_check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_check
     *
     * @param is_check the value for ecs_goods.is_check
     *
     * @mbg.generated
     */
    public void setIs_check(Boolean is_check) {
        this.is_check = is_check;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_catindex
     *
     * @return the value of ecs_goods.is_catindex
     *
     * @mbg.generated
     */
    public Boolean getIs_catindex() {
        return is_catindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_catindex
     *
     * @param is_catindex the value for ecs_goods.is_catindex
     *
     * @mbg.generated
     */
    public void setIs_catindex(Boolean is_catindex) {
        this.is_catindex = is_catindex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.cost_price
     *
     * @return the value of ecs_goods.cost_price
     *
     * @mbg.generated
     */
    public BigDecimal getCost_price() {
        return cost_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.cost_price
     *
     * @param cost_price the value for ecs_goods.cost_price
     *
     * @mbg.generated
     */
    public void setCost_price(BigDecimal cost_price) {
        this.cost_price = cost_price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.valid_date
     *
     * @return the value of ecs_goods.valid_date
     *
     * @mbg.generated
     */
    public Integer getValid_date() {
        return valid_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.valid_date
     *
     * @param valid_date the value for ecs_goods.valid_date
     *
     * @mbg.generated
     */
    public void setValid_date(Integer valid_date) {
        this.valid_date = valid_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.is_virtual
     *
     * @return the value of ecs_goods.is_virtual
     *
     * @mbg.generated
     */
    public Integer getIs_virtual() {
        return is_virtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.is_virtual
     *
     * @param is_virtual the value for ecs_goods.is_virtual
     *
     * @mbg.generated
     */
    public void setIs_virtual(Integer is_virtual) {
        this.is_virtual = is_virtual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.zq_source
     *
     * @return the value of ecs_goods.zq_source
     *
     * @mbg.generated
     */
    public String getZq_source() {
        return zq_source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.zq_source
     *
     * @param zq_source the value for ecs_goods.zq_source
     *
     * @mbg.generated
     */
    public void setZq_source(String zq_source) {
        this.zq_source = zq_source == null ? null : zq_source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.zq_id
     *
     * @return the value of ecs_goods.zq_id
     *
     * @mbg.generated
     */
    public String getZq_id() {
        return zq_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.zq_id
     *
     * @param zq_id the value for ecs_goods.zq_id
     *
     * @mbg.generated
     */
    public void setZq_id(String zq_id) {
        this.zq_id = zq_id == null ? null : zq_id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.goods_desc
     *
     * @return the value of ecs_goods.goods_desc
     *
     * @mbg.generated
     */
    public String getGoods_desc() {
        return goods_desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.goods_desc
     *
     * @param goods_desc the value for ecs_goods.goods_desc
     *
     * @mbg.generated
     */
    public void setGoods_desc(String goods_desc) {
        this.goods_desc = goods_desc == null ? null : goods_desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_goods.supplier_status_txt
     *
     * @return the value of ecs_goods.supplier_status_txt
     *
     * @mbg.generated
     */
    public String getSupplier_status_txt() {
        return supplier_status_txt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_goods.supplier_status_txt
     *
     * @param supplier_status_txt the value for ecs_goods.supplier_status_txt
     *
     * @mbg.generated
     */
    public void setSupplier_status_txt(String supplier_status_txt) {
        this.supplier_status_txt = supplier_status_txt == null ? null : supplier_status_txt.trim();
    }
}