package com.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class EcsOrderGoodsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public EcsOrderGoodsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andRec_idIsNull() {
            addCriterion("rec_id is null");
            return (Criteria) this;
        }

        public Criteria andRec_idIsNotNull() {
            addCriterion("rec_id is not null");
            return (Criteria) this;
        }

        public Criteria andRec_idEqualTo(Integer value) {
            addCriterion("rec_id =", value, "rec_id");
            return (Criteria) this;
        }

        public Criteria andRec_idNotEqualTo(Integer value) {
            addCriterion("rec_id <>", value, "rec_id");
            return (Criteria) this;
        }

        public Criteria andRec_idGreaterThan(Integer value) {
            addCriterion("rec_id >", value, "rec_id");
            return (Criteria) this;
        }

        public Criteria andRec_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("rec_id >=", value, "rec_id");
            return (Criteria) this;
        }

        public Criteria andRec_idLessThan(Integer value) {
            addCriterion("rec_id <", value, "rec_id");
            return (Criteria) this;
        }

        public Criteria andRec_idLessThanOrEqualTo(Integer value) {
            addCriterion("rec_id <=", value, "rec_id");
            return (Criteria) this;
        }

        public Criteria andRec_idIn(List<Integer> values) {
            addCriterion("rec_id in", values, "rec_id");
            return (Criteria) this;
        }

        public Criteria andRec_idNotIn(List<Integer> values) {
            addCriterion("rec_id not in", values, "rec_id");
            return (Criteria) this;
        }

        public Criteria andRec_idBetween(Integer value1, Integer value2) {
            addCriterion("rec_id between", value1, value2, "rec_id");
            return (Criteria) this;
        }

        public Criteria andRec_idNotBetween(Integer value1, Integer value2) {
            addCriterion("rec_id not between", value1, value2, "rec_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idIsNull() {
            addCriterion("order_id is null");
            return (Criteria) this;
        }

        public Criteria andOrder_idIsNotNull() {
            addCriterion("order_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_idEqualTo(Integer value) {
            addCriterion("order_id =", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idNotEqualTo(Integer value) {
            addCriterion("order_id <>", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idGreaterThan(Integer value) {
            addCriterion("order_id >", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("order_id >=", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idLessThan(Integer value) {
            addCriterion("order_id <", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idLessThanOrEqualTo(Integer value) {
            addCriterion("order_id <=", value, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idIn(List<Integer> values) {
            addCriterion("order_id in", values, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idNotIn(List<Integer> values) {
            addCriterion("order_id not in", values, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idBetween(Integer value1, Integer value2) {
            addCriterion("order_id between", value1, value2, "order_id");
            return (Criteria) this;
        }

        public Criteria andOrder_idNotBetween(Integer value1, Integer value2) {
            addCriterion("order_id not between", value1, value2, "order_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idIsNull() {
            addCriterion("goods_id is null");
            return (Criteria) this;
        }

        public Criteria andGoods_idIsNotNull() {
            addCriterion("goods_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoods_idEqualTo(Integer value) {
            addCriterion("goods_id =", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idNotEqualTo(Integer value) {
            addCriterion("goods_id <>", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idGreaterThan(Integer value) {
            addCriterion("goods_id >", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("goods_id >=", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idLessThan(Integer value) {
            addCriterion("goods_id <", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idLessThanOrEqualTo(Integer value) {
            addCriterion("goods_id <=", value, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idIn(List<Integer> values) {
            addCriterion("goods_id in", values, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idNotIn(List<Integer> values) {
            addCriterion("goods_id not in", values, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idBetween(Integer value1, Integer value2) {
            addCriterion("goods_id between", value1, value2, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_idNotBetween(Integer value1, Integer value2) {
            addCriterion("goods_id not between", value1, value2, "goods_id");
            return (Criteria) this;
        }

        public Criteria andGoods_nameIsNull() {
            addCriterion("goods_name is null");
            return (Criteria) this;
        }

        public Criteria andGoods_nameIsNotNull() {
            addCriterion("goods_name is not null");
            return (Criteria) this;
        }

        public Criteria andGoods_nameEqualTo(String value) {
            addCriterion("goods_name =", value, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameNotEqualTo(String value) {
            addCriterion("goods_name <>", value, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameGreaterThan(String value) {
            addCriterion("goods_name >", value, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameGreaterThanOrEqualTo(String value) {
            addCriterion("goods_name >=", value, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameLessThan(String value) {
            addCriterion("goods_name <", value, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameLessThanOrEqualTo(String value) {
            addCriterion("goods_name <=", value, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameLike(String value) {
            addCriterion("goods_name like", value, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameNotLike(String value) {
            addCriterion("goods_name not like", value, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameIn(List<String> values) {
            addCriterion("goods_name in", values, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameNotIn(List<String> values) {
            addCriterion("goods_name not in", values, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameBetween(String value1, String value2) {
            addCriterion("goods_name between", value1, value2, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_nameNotBetween(String value1, String value2) {
            addCriterion("goods_name not between", value1, value2, "goods_name");
            return (Criteria) this;
        }

        public Criteria andGoods_snIsNull() {
            addCriterion("goods_sn is null");
            return (Criteria) this;
        }

        public Criteria andGoods_snIsNotNull() {
            addCriterion("goods_sn is not null");
            return (Criteria) this;
        }

        public Criteria andGoods_snEqualTo(String value) {
            addCriterion("goods_sn =", value, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snNotEqualTo(String value) {
            addCriterion("goods_sn <>", value, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snGreaterThan(String value) {
            addCriterion("goods_sn >", value, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snGreaterThanOrEqualTo(String value) {
            addCriterion("goods_sn >=", value, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snLessThan(String value) {
            addCriterion("goods_sn <", value, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snLessThanOrEqualTo(String value) {
            addCriterion("goods_sn <=", value, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snLike(String value) {
            addCriterion("goods_sn like", value, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snNotLike(String value) {
            addCriterion("goods_sn not like", value, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snIn(List<String> values) {
            addCriterion("goods_sn in", values, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snNotIn(List<String> values) {
            addCriterion("goods_sn not in", values, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snBetween(String value1, String value2) {
            addCriterion("goods_sn between", value1, value2, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andGoods_snNotBetween(String value1, String value2) {
            addCriterion("goods_sn not between", value1, value2, "goods_sn");
            return (Criteria) this;
        }

        public Criteria andProduct_idIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProduct_idIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProduct_idEqualTo(Integer value) {
            addCriterion("product_id =", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idNotEqualTo(Integer value) {
            addCriterion("product_id <>", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idGreaterThan(Integer value) {
            addCriterion("product_id >", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("product_id >=", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idLessThan(Integer value) {
            addCriterion("product_id <", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idLessThanOrEqualTo(Integer value) {
            addCriterion("product_id <=", value, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idIn(List<Integer> values) {
            addCriterion("product_id in", values, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idNotIn(List<Integer> values) {
            addCriterion("product_id not in", values, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idBetween(Integer value1, Integer value2) {
            addCriterion("product_id between", value1, value2, "product_id");
            return (Criteria) this;
        }

        public Criteria andProduct_idNotBetween(Integer value1, Integer value2) {
            addCriterion("product_id not between", value1, value2, "product_id");
            return (Criteria) this;
        }

        public Criteria andGoods_numberIsNull() {
            addCriterion("goods_number is null");
            return (Criteria) this;
        }

        public Criteria andGoods_numberIsNotNull() {
            addCriterion("goods_number is not null");
            return (Criteria) this;
        }

        public Criteria andGoods_numberEqualTo(Short value) {
            addCriterion("goods_number =", value, "goods_number");
            return (Criteria) this;
        }

        public Criteria andGoods_numberNotEqualTo(Short value) {
            addCriterion("goods_number <>", value, "goods_number");
            return (Criteria) this;
        }

        public Criteria andGoods_numberGreaterThan(Short value) {
            addCriterion("goods_number >", value, "goods_number");
            return (Criteria) this;
        }

        public Criteria andGoods_numberGreaterThanOrEqualTo(Short value) {
            addCriterion("goods_number >=", value, "goods_number");
            return (Criteria) this;
        }

        public Criteria andGoods_numberLessThan(Short value) {
            addCriterion("goods_number <", value, "goods_number");
            return (Criteria) this;
        }

        public Criteria andGoods_numberLessThanOrEqualTo(Short value) {
            addCriterion("goods_number <=", value, "goods_number");
            return (Criteria) this;
        }

        public Criteria andGoods_numberIn(List<Short> values) {
            addCriterion("goods_number in", values, "goods_number");
            return (Criteria) this;
        }

        public Criteria andGoods_numberNotIn(List<Short> values) {
            addCriterion("goods_number not in", values, "goods_number");
            return (Criteria) this;
        }

        public Criteria andGoods_numberBetween(Short value1, Short value2) {
            addCriterion("goods_number between", value1, value2, "goods_number");
            return (Criteria) this;
        }

        public Criteria andGoods_numberNotBetween(Short value1, Short value2) {
            addCriterion("goods_number not between", value1, value2, "goods_number");
            return (Criteria) this;
        }

        public Criteria andMarket_priceIsNull() {
            addCriterion("market_price is null");
            return (Criteria) this;
        }

        public Criteria andMarket_priceIsNotNull() {
            addCriterion("market_price is not null");
            return (Criteria) this;
        }

        public Criteria andMarket_priceEqualTo(BigDecimal value) {
            addCriterion("market_price =", value, "market_price");
            return (Criteria) this;
        }

        public Criteria andMarket_priceNotEqualTo(BigDecimal value) {
            addCriterion("market_price <>", value, "market_price");
            return (Criteria) this;
        }

        public Criteria andMarket_priceGreaterThan(BigDecimal value) {
            addCriterion("market_price >", value, "market_price");
            return (Criteria) this;
        }

        public Criteria andMarket_priceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("market_price >=", value, "market_price");
            return (Criteria) this;
        }

        public Criteria andMarket_priceLessThan(BigDecimal value) {
            addCriterion("market_price <", value, "market_price");
            return (Criteria) this;
        }

        public Criteria andMarket_priceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("market_price <=", value, "market_price");
            return (Criteria) this;
        }

        public Criteria andMarket_priceIn(List<BigDecimal> values) {
            addCriterion("market_price in", values, "market_price");
            return (Criteria) this;
        }

        public Criteria andMarket_priceNotIn(List<BigDecimal> values) {
            addCriterion("market_price not in", values, "market_price");
            return (Criteria) this;
        }

        public Criteria andMarket_priceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("market_price between", value1, value2, "market_price");
            return (Criteria) this;
        }

        public Criteria andMarket_priceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("market_price not between", value1, value2, "market_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceIsNull() {
            addCriterion("goods_price is null");
            return (Criteria) this;
        }

        public Criteria andGoods_priceIsNotNull() {
            addCriterion("goods_price is not null");
            return (Criteria) this;
        }

        public Criteria andGoods_priceEqualTo(BigDecimal value) {
            addCriterion("goods_price =", value, "goods_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceNotEqualTo(BigDecimal value) {
            addCriterion("goods_price <>", value, "goods_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceGreaterThan(BigDecimal value) {
            addCriterion("goods_price >", value, "goods_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_price >=", value, "goods_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceLessThan(BigDecimal value) {
            addCriterion("goods_price <", value, "goods_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_price <=", value, "goods_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceIn(List<BigDecimal> values) {
            addCriterion("goods_price in", values, "goods_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceNotIn(List<BigDecimal> values) {
            addCriterion("goods_price not in", values, "goods_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_price between", value1, value2, "goods_price");
            return (Criteria) this;
        }

        public Criteria andGoods_priceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_price not between", value1, value2, "goods_price");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyIsNull() {
            addCriterion("split_money is null");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyIsNotNull() {
            addCriterion("split_money is not null");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyEqualTo(BigDecimal value) {
            addCriterion("split_money =", value, "split_money");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyNotEqualTo(BigDecimal value) {
            addCriterion("split_money <>", value, "split_money");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyGreaterThan(BigDecimal value) {
            addCriterion("split_money >", value, "split_money");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("split_money >=", value, "split_money");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyLessThan(BigDecimal value) {
            addCriterion("split_money <", value, "split_money");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("split_money <=", value, "split_money");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyIn(List<BigDecimal> values) {
            addCriterion("split_money in", values, "split_money");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyNotIn(List<BigDecimal> values) {
            addCriterion("split_money not in", values, "split_money");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("split_money between", value1, value2, "split_money");
            return (Criteria) this;
        }

        public Criteria andSplit_moneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("split_money not between", value1, value2, "split_money");
            return (Criteria) this;
        }

        public Criteria andSend_numberIsNull() {
            addCriterion("send_number is null");
            return (Criteria) this;
        }

        public Criteria andSend_numberIsNotNull() {
            addCriterion("send_number is not null");
            return (Criteria) this;
        }

        public Criteria andSend_numberEqualTo(Short value) {
            addCriterion("send_number =", value, "send_number");
            return (Criteria) this;
        }

        public Criteria andSend_numberNotEqualTo(Short value) {
            addCriterion("send_number <>", value, "send_number");
            return (Criteria) this;
        }

        public Criteria andSend_numberGreaterThan(Short value) {
            addCriterion("send_number >", value, "send_number");
            return (Criteria) this;
        }

        public Criteria andSend_numberGreaterThanOrEqualTo(Short value) {
            addCriterion("send_number >=", value, "send_number");
            return (Criteria) this;
        }

        public Criteria andSend_numberLessThan(Short value) {
            addCriterion("send_number <", value, "send_number");
            return (Criteria) this;
        }

        public Criteria andSend_numberLessThanOrEqualTo(Short value) {
            addCriterion("send_number <=", value, "send_number");
            return (Criteria) this;
        }

        public Criteria andSend_numberIn(List<Short> values) {
            addCriterion("send_number in", values, "send_number");
            return (Criteria) this;
        }

        public Criteria andSend_numberNotIn(List<Short> values) {
            addCriterion("send_number not in", values, "send_number");
            return (Criteria) this;
        }

        public Criteria andSend_numberBetween(Short value1, Short value2) {
            addCriterion("send_number between", value1, value2, "send_number");
            return (Criteria) this;
        }

        public Criteria andSend_numberNotBetween(Short value1, Short value2) {
            addCriterion("send_number not between", value1, value2, "send_number");
            return (Criteria) this;
        }

        public Criteria andIs_realIsNull() {
            addCriterion("is_real is null");
            return (Criteria) this;
        }

        public Criteria andIs_realIsNotNull() {
            addCriterion("is_real is not null");
            return (Criteria) this;
        }

        public Criteria andIs_realEqualTo(Boolean value) {
            addCriterion("is_real =", value, "is_real");
            return (Criteria) this;
        }

        public Criteria andIs_realNotEqualTo(Boolean value) {
            addCriterion("is_real <>", value, "is_real");
            return (Criteria) this;
        }

        public Criteria andIs_realGreaterThan(Boolean value) {
            addCriterion("is_real >", value, "is_real");
            return (Criteria) this;
        }

        public Criteria andIs_realGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_real >=", value, "is_real");
            return (Criteria) this;
        }

        public Criteria andIs_realLessThan(Boolean value) {
            addCriterion("is_real <", value, "is_real");
            return (Criteria) this;
        }

        public Criteria andIs_realLessThanOrEqualTo(Boolean value) {
            addCriterion("is_real <=", value, "is_real");
            return (Criteria) this;
        }

        public Criteria andIs_realIn(List<Boolean> values) {
            addCriterion("is_real in", values, "is_real");
            return (Criteria) this;
        }

        public Criteria andIs_realNotIn(List<Boolean> values) {
            addCriterion("is_real not in", values, "is_real");
            return (Criteria) this;
        }

        public Criteria andIs_realBetween(Boolean value1, Boolean value2) {
            addCriterion("is_real between", value1, value2, "is_real");
            return (Criteria) this;
        }

        public Criteria andIs_realNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_real not between", value1, value2, "is_real");
            return (Criteria) this;
        }

        public Criteria andExtension_codeIsNull() {
            addCriterion("extension_code is null");
            return (Criteria) this;
        }

        public Criteria andExtension_codeIsNotNull() {
            addCriterion("extension_code is not null");
            return (Criteria) this;
        }

        public Criteria andExtension_codeEqualTo(String value) {
            addCriterion("extension_code =", value, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeNotEqualTo(String value) {
            addCriterion("extension_code <>", value, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeGreaterThan(String value) {
            addCriterion("extension_code >", value, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeGreaterThanOrEqualTo(String value) {
            addCriterion("extension_code >=", value, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeLessThan(String value) {
            addCriterion("extension_code <", value, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeLessThanOrEqualTo(String value) {
            addCriterion("extension_code <=", value, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeLike(String value) {
            addCriterion("extension_code like", value, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeNotLike(String value) {
            addCriterion("extension_code not like", value, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeIn(List<String> values) {
            addCriterion("extension_code in", values, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeNotIn(List<String> values) {
            addCriterion("extension_code not in", values, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeBetween(String value1, String value2) {
            addCriterion("extension_code between", value1, value2, "extension_code");
            return (Criteria) this;
        }

        public Criteria andExtension_codeNotBetween(String value1, String value2) {
            addCriterion("extension_code not between", value1, value2, "extension_code");
            return (Criteria) this;
        }

        public Criteria andParent_idIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParent_idIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParent_idEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idLessThan(Integer value) {
            addCriterion("parent_id <", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parent_id");
            return (Criteria) this;
        }

        public Criteria andIs_giftIsNull() {
            addCriterion("is_gift is null");
            return (Criteria) this;
        }

        public Criteria andIs_giftIsNotNull() {
            addCriterion("is_gift is not null");
            return (Criteria) this;
        }

        public Criteria andIs_giftEqualTo(Short value) {
            addCriterion("is_gift =", value, "is_gift");
            return (Criteria) this;
        }

        public Criteria andIs_giftNotEqualTo(Short value) {
            addCriterion("is_gift <>", value, "is_gift");
            return (Criteria) this;
        }

        public Criteria andIs_giftGreaterThan(Short value) {
            addCriterion("is_gift >", value, "is_gift");
            return (Criteria) this;
        }

        public Criteria andIs_giftGreaterThanOrEqualTo(Short value) {
            addCriterion("is_gift >=", value, "is_gift");
            return (Criteria) this;
        }

        public Criteria andIs_giftLessThan(Short value) {
            addCriterion("is_gift <", value, "is_gift");
            return (Criteria) this;
        }

        public Criteria andIs_giftLessThanOrEqualTo(Short value) {
            addCriterion("is_gift <=", value, "is_gift");
            return (Criteria) this;
        }

        public Criteria andIs_giftIn(List<Short> values) {
            addCriterion("is_gift in", values, "is_gift");
            return (Criteria) this;
        }

        public Criteria andIs_giftNotIn(List<Short> values) {
            addCriterion("is_gift not in", values, "is_gift");
            return (Criteria) this;
        }

        public Criteria andIs_giftBetween(Short value1, Short value2) {
            addCriterion("is_gift between", value1, value2, "is_gift");
            return (Criteria) this;
        }

        public Criteria andIs_giftNotBetween(Short value1, Short value2) {
            addCriterion("is_gift not between", value1, value2, "is_gift");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idIsNull() {
            addCriterion("goods_attr_id is null");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idIsNotNull() {
            addCriterion("goods_attr_id is not null");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idEqualTo(String value) {
            addCriterion("goods_attr_id =", value, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idNotEqualTo(String value) {
            addCriterion("goods_attr_id <>", value, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idGreaterThan(String value) {
            addCriterion("goods_attr_id >", value, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idGreaterThanOrEqualTo(String value) {
            addCriterion("goods_attr_id >=", value, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idLessThan(String value) {
            addCriterion("goods_attr_id <", value, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idLessThanOrEqualTo(String value) {
            addCriterion("goods_attr_id <=", value, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idLike(String value) {
            addCriterion("goods_attr_id like", value, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idNotLike(String value) {
            addCriterion("goods_attr_id not like", value, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idIn(List<String> values) {
            addCriterion("goods_attr_id in", values, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idNotIn(List<String> values) {
            addCriterion("goods_attr_id not in", values, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idBetween(String value1, String value2) {
            addCriterion("goods_attr_id between", value1, value2, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andGoods_attr_idNotBetween(String value1, String value2) {
            addCriterion("goods_attr_id not between", value1, value2, "goods_attr_id");
            return (Criteria) this;
        }

        public Criteria andComment_stateIsNull() {
            addCriterion("comment_state is null");
            return (Criteria) this;
        }

        public Criteria andComment_stateIsNotNull() {
            addCriterion("comment_state is not null");
            return (Criteria) this;
        }

        public Criteria andComment_stateEqualTo(Boolean value) {
            addCriterion("comment_state =", value, "comment_state");
            return (Criteria) this;
        }

        public Criteria andComment_stateNotEqualTo(Boolean value) {
            addCriterion("comment_state <>", value, "comment_state");
            return (Criteria) this;
        }

        public Criteria andComment_stateGreaterThan(Boolean value) {
            addCriterion("comment_state >", value, "comment_state");
            return (Criteria) this;
        }

        public Criteria andComment_stateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("comment_state >=", value, "comment_state");
            return (Criteria) this;
        }

        public Criteria andComment_stateLessThan(Boolean value) {
            addCriterion("comment_state <", value, "comment_state");
            return (Criteria) this;
        }

        public Criteria andComment_stateLessThanOrEqualTo(Boolean value) {
            addCriterion("comment_state <=", value, "comment_state");
            return (Criteria) this;
        }

        public Criteria andComment_stateIn(List<Boolean> values) {
            addCriterion("comment_state in", values, "comment_state");
            return (Criteria) this;
        }

        public Criteria andComment_stateNotIn(List<Boolean> values) {
            addCriterion("comment_state not in", values, "comment_state");
            return (Criteria) this;
        }

        public Criteria andComment_stateBetween(Boolean value1, Boolean value2) {
            addCriterion("comment_state between", value1, value2, "comment_state");
            return (Criteria) this;
        }

        public Criteria andComment_stateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("comment_state not between", value1, value2, "comment_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateIsNull() {
            addCriterion("shaidan_state is null");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateIsNotNull() {
            addCriterion("shaidan_state is not null");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateEqualTo(Boolean value) {
            addCriterion("shaidan_state =", value, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateNotEqualTo(Boolean value) {
            addCriterion("shaidan_state <>", value, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateGreaterThan(Boolean value) {
            addCriterion("shaidan_state >", value, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateGreaterThanOrEqualTo(Boolean value) {
            addCriterion("shaidan_state >=", value, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateLessThan(Boolean value) {
            addCriterion("shaidan_state <", value, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateLessThanOrEqualTo(Boolean value) {
            addCriterion("shaidan_state <=", value, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateIn(List<Boolean> values) {
            addCriterion("shaidan_state in", values, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateNotIn(List<Boolean> values) {
            addCriterion("shaidan_state not in", values, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateBetween(Boolean value1, Boolean value2) {
            addCriterion("shaidan_state between", value1, value2, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andShaidan_stateNotBetween(Boolean value1, Boolean value2) {
            addCriterion("shaidan_state not between", value1, value2, "shaidan_state");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idIsNull() {
            addCriterion("package_attr_id is null");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idIsNotNull() {
            addCriterion("package_attr_id is not null");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idEqualTo(String value) {
            addCriterion("package_attr_id =", value, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idNotEqualTo(String value) {
            addCriterion("package_attr_id <>", value, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idGreaterThan(String value) {
            addCriterion("package_attr_id >", value, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idGreaterThanOrEqualTo(String value) {
            addCriterion("package_attr_id >=", value, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idLessThan(String value) {
            addCriterion("package_attr_id <", value, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idLessThanOrEqualTo(String value) {
            addCriterion("package_attr_id <=", value, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idLike(String value) {
            addCriterion("package_attr_id like", value, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idNotLike(String value) {
            addCriterion("package_attr_id not like", value, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idIn(List<String> values) {
            addCriterion("package_attr_id in", values, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idNotIn(List<String> values) {
            addCriterion("package_attr_id not in", values, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idBetween(String value1, String value2) {
            addCriterion("package_attr_id between", value1, value2, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andPackage_attr_idNotBetween(String value1, String value2) {
            addCriterion("package_attr_id not between", value1, value2, "package_attr_id");
            return (Criteria) this;
        }

        public Criteria andIs_backIsNull() {
            addCriterion("is_back is null");
            return (Criteria) this;
        }

        public Criteria andIs_backIsNotNull() {
            addCriterion("is_back is not null");
            return (Criteria) this;
        }

        public Criteria andIs_backEqualTo(Boolean value) {
            addCriterion("is_back =", value, "is_back");
            return (Criteria) this;
        }

        public Criteria andIs_backNotEqualTo(Boolean value) {
            addCriterion("is_back <>", value, "is_back");
            return (Criteria) this;
        }

        public Criteria andIs_backGreaterThan(Boolean value) {
            addCriterion("is_back >", value, "is_back");
            return (Criteria) this;
        }

        public Criteria andIs_backGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_back >=", value, "is_back");
            return (Criteria) this;
        }

        public Criteria andIs_backLessThan(Boolean value) {
            addCriterion("is_back <", value, "is_back");
            return (Criteria) this;
        }

        public Criteria andIs_backLessThanOrEqualTo(Boolean value) {
            addCriterion("is_back <=", value, "is_back");
            return (Criteria) this;
        }

        public Criteria andIs_backIn(List<Boolean> values) {
            addCriterion("is_back in", values, "is_back");
            return (Criteria) this;
        }

        public Criteria andIs_backNotIn(List<Boolean> values) {
            addCriterion("is_back not in", values, "is_back");
            return (Criteria) this;
        }

        public Criteria andIs_backBetween(Boolean value1, Boolean value2) {
            addCriterion("is_back between", value1, value2, "is_back");
            return (Criteria) this;
        }

        public Criteria andIs_backNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_back not between", value1, value2, "is_back");
            return (Criteria) this;
        }

        public Criteria andCost_priceIsNull() {
            addCriterion("cost_price is null");
            return (Criteria) this;
        }

        public Criteria andCost_priceIsNotNull() {
            addCriterion("cost_price is not null");
            return (Criteria) this;
        }

        public Criteria andCost_priceEqualTo(BigDecimal value) {
            addCriterion("cost_price =", value, "cost_price");
            return (Criteria) this;
        }

        public Criteria andCost_priceNotEqualTo(BigDecimal value) {
            addCriterion("cost_price <>", value, "cost_price");
            return (Criteria) this;
        }

        public Criteria andCost_priceGreaterThan(BigDecimal value) {
            addCriterion("cost_price >", value, "cost_price");
            return (Criteria) this;
        }

        public Criteria andCost_priceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cost_price >=", value, "cost_price");
            return (Criteria) this;
        }

        public Criteria andCost_priceLessThan(BigDecimal value) {
            addCriterion("cost_price <", value, "cost_price");
            return (Criteria) this;
        }

        public Criteria andCost_priceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cost_price <=", value, "cost_price");
            return (Criteria) this;
        }

        public Criteria andCost_priceIn(List<BigDecimal> values) {
            addCriterion("cost_price in", values, "cost_price");
            return (Criteria) this;
        }

        public Criteria andCost_priceNotIn(List<BigDecimal> values) {
            addCriterion("cost_price not in", values, "cost_price");
            return (Criteria) this;
        }

        public Criteria andCost_priceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost_price between", value1, value2, "cost_price");
            return (Criteria) this;
        }

        public Criteria andCost_priceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cost_price not between", value1, value2, "cost_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceIsNull() {
            addCriterion("promote_price is null");
            return (Criteria) this;
        }

        public Criteria andPromote_priceIsNotNull() {
            addCriterion("promote_price is not null");
            return (Criteria) this;
        }

        public Criteria andPromote_priceEqualTo(BigDecimal value) {
            addCriterion("promote_price =", value, "promote_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceNotEqualTo(BigDecimal value) {
            addCriterion("promote_price <>", value, "promote_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceGreaterThan(BigDecimal value) {
            addCriterion("promote_price >", value, "promote_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("promote_price >=", value, "promote_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceLessThan(BigDecimal value) {
            addCriterion("promote_price <", value, "promote_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("promote_price <=", value, "promote_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceIn(List<BigDecimal> values) {
            addCriterion("promote_price in", values, "promote_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceNotIn(List<BigDecimal> values) {
            addCriterion("promote_price not in", values, "promote_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promote_price between", value1, value2, "promote_price");
            return (Criteria) this;
        }

        public Criteria andPromote_priceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("promote_price not between", value1, value2, "promote_price");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ecs_order_goods
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ecs_order_goods
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}