package com.entity;

public class EcsRegFields {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_reg_fields.id
     *
     * @mbg.generated
     */
    private Byte id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_reg_fields.reg_field_name
     *
     * @mbg.generated
     */
    private String reg_field_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_reg_fields.dis_order
     *
     * @mbg.generated
     */
    private Byte dis_order;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_reg_fields.display
     *
     * @mbg.generated
     */
    private Boolean display;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_reg_fields.type
     *
     * @mbg.generated
     */
    private Boolean type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_reg_fields.is_need
     *
     * @mbg.generated
     */
    private Boolean is_need;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_reg_fields.id
     *
     * @return the value of ecs_reg_fields.id
     *
     * @mbg.generated
     */
    public Byte getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_reg_fields.id
     *
     * @param id the value for ecs_reg_fields.id
     *
     * @mbg.generated
     */
    public void setId(Byte id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_reg_fields.reg_field_name
     *
     * @return the value of ecs_reg_fields.reg_field_name
     *
     * @mbg.generated
     */
    public String getReg_field_name() {
        return reg_field_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_reg_fields.reg_field_name
     *
     * @param reg_field_name the value for ecs_reg_fields.reg_field_name
     *
     * @mbg.generated
     */
    public void setReg_field_name(String reg_field_name) {
        this.reg_field_name = reg_field_name == null ? null : reg_field_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_reg_fields.dis_order
     *
     * @return the value of ecs_reg_fields.dis_order
     *
     * @mbg.generated
     */
    public Byte getDis_order() {
        return dis_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_reg_fields.dis_order
     *
     * @param dis_order the value for ecs_reg_fields.dis_order
     *
     * @mbg.generated
     */
    public void setDis_order(Byte dis_order) {
        this.dis_order = dis_order;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_reg_fields.display
     *
     * @return the value of ecs_reg_fields.display
     *
     * @mbg.generated
     */
    public Boolean getDisplay() {
        return display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_reg_fields.display
     *
     * @param display the value for ecs_reg_fields.display
     *
     * @mbg.generated
     */
    public void setDisplay(Boolean display) {
        this.display = display;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_reg_fields.type
     *
     * @return the value of ecs_reg_fields.type
     *
     * @mbg.generated
     */
    public Boolean getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_reg_fields.type
     *
     * @param type the value for ecs_reg_fields.type
     *
     * @mbg.generated
     */
    public void setType(Boolean type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_reg_fields.is_need
     *
     * @return the value of ecs_reg_fields.is_need
     *
     * @mbg.generated
     */
    public Boolean getIs_need() {
        return is_need;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_reg_fields.is_need
     *
     * @param is_need the value for ecs_reg_fields.is_need
     *
     * @mbg.generated
     */
    public void setIs_need(Boolean is_need) {
        this.is_need = is_need;
    }
}