package com.entity;

import java.util.ArrayList;
import java.util.List;

public class EcsSupplierTagExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public EcsSupplierTagExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTag_idIsNull() {
            addCriterion("tag_id is null");
            return (Criteria) this;
        }

        public Criteria andTag_idIsNotNull() {
            addCriterion("tag_id is not null");
            return (Criteria) this;
        }

        public Criteria andTag_idEqualTo(Integer value) {
            addCriterion("tag_id =", value, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_idNotEqualTo(Integer value) {
            addCriterion("tag_id <>", value, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_idGreaterThan(Integer value) {
            addCriterion("tag_id >", value, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("tag_id >=", value, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_idLessThan(Integer value) {
            addCriterion("tag_id <", value, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_idLessThanOrEqualTo(Integer value) {
            addCriterion("tag_id <=", value, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_idIn(List<Integer> values) {
            addCriterion("tag_id in", values, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_idNotIn(List<Integer> values) {
            addCriterion("tag_id not in", values, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_idBetween(Integer value1, Integer value2) {
            addCriterion("tag_id between", value1, value2, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_idNotBetween(Integer value1, Integer value2) {
            addCriterion("tag_id not between", value1, value2, "tag_id");
            return (Criteria) this;
        }

        public Criteria andTag_nameIsNull() {
            addCriterion("tag_name is null");
            return (Criteria) this;
        }

        public Criteria andTag_nameIsNotNull() {
            addCriterion("tag_name is not null");
            return (Criteria) this;
        }

        public Criteria andTag_nameEqualTo(String value) {
            addCriterion("tag_name =", value, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameNotEqualTo(String value) {
            addCriterion("tag_name <>", value, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameGreaterThan(String value) {
            addCriterion("tag_name >", value, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameGreaterThanOrEqualTo(String value) {
            addCriterion("tag_name >=", value, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameLessThan(String value) {
            addCriterion("tag_name <", value, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameLessThanOrEqualTo(String value) {
            addCriterion("tag_name <=", value, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameLike(String value) {
            addCriterion("tag_name like", value, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameNotLike(String value) {
            addCriterion("tag_name not like", value, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameIn(List<String> values) {
            addCriterion("tag_name in", values, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameNotIn(List<String> values) {
            addCriterion("tag_name not in", values, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameBetween(String value1, String value2) {
            addCriterion("tag_name between", value1, value2, "tag_name");
            return (Criteria) this;
        }

        public Criteria andTag_nameNotBetween(String value1, String value2) {
            addCriterion("tag_name not between", value1, value2, "tag_name");
            return (Criteria) this;
        }

        public Criteria andIs_groomIsNull() {
            addCriterion("is_groom is null");
            return (Criteria) this;
        }

        public Criteria andIs_groomIsNotNull() {
            addCriterion("is_groom is not null");
            return (Criteria) this;
        }

        public Criteria andIs_groomEqualTo(Byte value) {
            addCriterion("is_groom =", value, "is_groom");
            return (Criteria) this;
        }

        public Criteria andIs_groomNotEqualTo(Byte value) {
            addCriterion("is_groom <>", value, "is_groom");
            return (Criteria) this;
        }

        public Criteria andIs_groomGreaterThan(Byte value) {
            addCriterion("is_groom >", value, "is_groom");
            return (Criteria) this;
        }

        public Criteria andIs_groomGreaterThanOrEqualTo(Byte value) {
            addCriterion("is_groom >=", value, "is_groom");
            return (Criteria) this;
        }

        public Criteria andIs_groomLessThan(Byte value) {
            addCriterion("is_groom <", value, "is_groom");
            return (Criteria) this;
        }

        public Criteria andIs_groomLessThanOrEqualTo(Byte value) {
            addCriterion("is_groom <=", value, "is_groom");
            return (Criteria) this;
        }

        public Criteria andIs_groomIn(List<Byte> values) {
            addCriterion("is_groom in", values, "is_groom");
            return (Criteria) this;
        }

        public Criteria andIs_groomNotIn(List<Byte> values) {
            addCriterion("is_groom not in", values, "is_groom");
            return (Criteria) this;
        }

        public Criteria andIs_groomBetween(Byte value1, Byte value2) {
            addCriterion("is_groom between", value1, value2, "is_groom");
            return (Criteria) this;
        }

        public Criteria andIs_groomNotBetween(Byte value1, Byte value2) {
            addCriterion("is_groom not between", value1, value2, "is_groom");
            return (Criteria) this;
        }

        public Criteria andSort_orderIsNull() {
            addCriterion("sort_order is null");
            return (Criteria) this;
        }

        public Criteria andSort_orderIsNotNull() {
            addCriterion("sort_order is not null");
            return (Criteria) this;
        }

        public Criteria andSort_orderEqualTo(Byte value) {
            addCriterion("sort_order =", value, "sort_order");
            return (Criteria) this;
        }

        public Criteria andSort_orderNotEqualTo(Byte value) {
            addCriterion("sort_order <>", value, "sort_order");
            return (Criteria) this;
        }

        public Criteria andSort_orderGreaterThan(Byte value) {
            addCriterion("sort_order >", value, "sort_order");
            return (Criteria) this;
        }

        public Criteria andSort_orderGreaterThanOrEqualTo(Byte value) {
            addCriterion("sort_order >=", value, "sort_order");
            return (Criteria) this;
        }

        public Criteria andSort_orderLessThan(Byte value) {
            addCriterion("sort_order <", value, "sort_order");
            return (Criteria) this;
        }

        public Criteria andSort_orderLessThanOrEqualTo(Byte value) {
            addCriterion("sort_order <=", value, "sort_order");
            return (Criteria) this;
        }

        public Criteria andSort_orderIn(List<Byte> values) {
            addCriterion("sort_order in", values, "sort_order");
            return (Criteria) this;
        }

        public Criteria andSort_orderNotIn(List<Byte> values) {
            addCriterion("sort_order not in", values, "sort_order");
            return (Criteria) this;
        }

        public Criteria andSort_orderBetween(Byte value1, Byte value2) {
            addCriterion("sort_order between", value1, value2, "sort_order");
            return (Criteria) this;
        }

        public Criteria andSort_orderNotBetween(Byte value1, Byte value2) {
            addCriterion("sort_order not between", value1, value2, "sort_order");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ecs_supplier_tag
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}