package com.entity;

public class EcsVolumePriceKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_volume_price.price_type
     *
     * @mbg.generated
     */
    private Boolean price_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_volume_price.goods_id
     *
     * @mbg.generated
     */
    private Integer goods_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecs_volume_price.volume_number
     *
     * @mbg.generated
     */
    private Short volume_number;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_volume_price.price_type
     *
     * @return the value of ecs_volume_price.price_type
     *
     * @mbg.generated
     */
    public Boolean getPrice_type() {
        return price_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_volume_price.price_type
     *
     * @param price_type the value for ecs_volume_price.price_type
     *
     * @mbg.generated
     */
    public void setPrice_type(Boolean price_type) {
        this.price_type = price_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_volume_price.goods_id
     *
     * @return the value of ecs_volume_price.goods_id
     *
     * @mbg.generated
     */
    public Integer getGoods_id() {
        return goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_volume_price.goods_id
     *
     * @param goods_id the value for ecs_volume_price.goods_id
     *
     * @mbg.generated
     */
    public void setGoods_id(Integer goods_id) {
        this.goods_id = goods_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecs_volume_price.volume_number
     *
     * @return the value of ecs_volume_price.volume_number
     *
     * @mbg.generated
     */
    public Short getVolume_number() {
        return volume_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecs_volume_price.volume_number
     *
     * @param volume_number the value for ecs_volume_price.volume_number
     *
     * @mbg.generated
     */
    public void setVolume_number(Short volume_number) {
        this.volume_number = volume_number;
    }
}