package com.entity;

public class InnodbIndexes {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_INDEXES.INDEX_ID
     *
     * @mbg.generated
     */
    private Long INDEX_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_INDEXES.NAME
     *
     * @mbg.generated
     */
    private String NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_INDEXES.TABLE_ID
     *
     * @mbg.generated
     */
    private Long TABLE_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_INDEXES.TYPE
     *
     * @mbg.generated
     */
    private Integer TYPE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_INDEXES.N_FIELDS
     *
     * @mbg.generated
     */
    private Integer n_FIELDS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_INDEXES.PAGE_NO
     *
     * @mbg.generated
     */
    private Integer PAGE_NO;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_INDEXES.SPACE
     *
     * @mbg.generated
     */
    private Integer SPACE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_INDEXES.MERGE_THRESHOLD
     *
     * @mbg.generated
     */
    private Integer MERGE_THRESHOLD;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_INDEXES.INDEX_ID
     *
     * @return the value of INNODB_INDEXES.INDEX_ID
     *
     * @mbg.generated
     */
    public Long getINDEX_ID() {
        return INDEX_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_INDEXES.INDEX_ID
     *
     * @param INDEX_ID the value for INNODB_INDEXES.INDEX_ID
     *
     * @mbg.generated
     */
    public void setINDEX_ID(Long INDEX_ID) {
        this.INDEX_ID = INDEX_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_INDEXES.NAME
     *
     * @return the value of INNODB_INDEXES.NAME
     *
     * @mbg.generated
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_INDEXES.NAME
     *
     * @param NAME the value for INNODB_INDEXES.NAME
     *
     * @mbg.generated
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_INDEXES.TABLE_ID
     *
     * @return the value of INNODB_INDEXES.TABLE_ID
     *
     * @mbg.generated
     */
    public Long getTABLE_ID() {
        return TABLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_INDEXES.TABLE_ID
     *
     * @param TABLE_ID the value for INNODB_INDEXES.TABLE_ID
     *
     * @mbg.generated
     */
    public void setTABLE_ID(Long TABLE_ID) {
        this.TABLE_ID = TABLE_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_INDEXES.TYPE
     *
     * @return the value of INNODB_INDEXES.TYPE
     *
     * @mbg.generated
     */
    public Integer getTYPE() {
        return TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_INDEXES.TYPE
     *
     * @param TYPE the value for INNODB_INDEXES.TYPE
     *
     * @mbg.generated
     */
    public void setTYPE(Integer TYPE) {
        this.TYPE = TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_INDEXES.N_FIELDS
     *
     * @return the value of INNODB_INDEXES.N_FIELDS
     *
     * @mbg.generated
     */
    public Integer getN_FIELDS() {
        return n_FIELDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_INDEXES.N_FIELDS
     *
     * @param n_FIELDS the value for INNODB_INDEXES.N_FIELDS
     *
     * @mbg.generated
     */
    public void setN_FIELDS(Integer n_FIELDS) {
        this.n_FIELDS = n_FIELDS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_INDEXES.PAGE_NO
     *
     * @return the value of INNODB_INDEXES.PAGE_NO
     *
     * @mbg.generated
     */
    public Integer getPAGE_NO() {
        return PAGE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_INDEXES.PAGE_NO
     *
     * @param PAGE_NO the value for INNODB_INDEXES.PAGE_NO
     *
     * @mbg.generated
     */
    public void setPAGE_NO(Integer PAGE_NO) {
        this.PAGE_NO = PAGE_NO;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_INDEXES.SPACE
     *
     * @return the value of INNODB_INDEXES.SPACE
     *
     * @mbg.generated
     */
    public Integer getSPACE() {
        return SPACE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_INDEXES.SPACE
     *
     * @param SPACE the value for INNODB_INDEXES.SPACE
     *
     * @mbg.generated
     */
    public void setSPACE(Integer SPACE) {
        this.SPACE = SPACE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_INDEXES.MERGE_THRESHOLD
     *
     * @return the value of INNODB_INDEXES.MERGE_THRESHOLD
     *
     * @mbg.generated
     */
    public Integer getMERGE_THRESHOLD() {
        return MERGE_THRESHOLD;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_INDEXES.MERGE_THRESHOLD
     *
     * @param MERGE_THRESHOLD the value for INNODB_INDEXES.MERGE_THRESHOLD
     *
     * @mbg.generated
     */
    public void setMERGE_THRESHOLD(Integer MERGE_THRESHOLD) {
        this.MERGE_THRESHOLD = MERGE_THRESHOLD;
    }
}