package com.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class InnodbMetricsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public InnodbMetricsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andNAMEIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNAMEIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNAMEEqualTo(String value) {
            addCriterion("NAME =", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotEqualTo(String value) {
            addCriterion("NAME <>", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEGreaterThan(String value) {
            addCriterion("NAME >", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELessThan(String value) {
            addCriterion("NAME <", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMELike(String value) {
            addCriterion("NAME like", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotLike(String value) {
            addCriterion("NAME not like", value, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEIn(List<String> values) {
            addCriterion("NAME in", values, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotIn(List<String> values) {
            addCriterion("NAME not in", values, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMEBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "NAME");
            return (Criteria) this;
        }

        public Criteria andNAMENotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "NAME");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMIsNull() {
            addCriterion("SUBSYSTEM is null");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMIsNotNull() {
            addCriterion("SUBSYSTEM is not null");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMEqualTo(String value) {
            addCriterion("SUBSYSTEM =", value, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMNotEqualTo(String value) {
            addCriterion("SUBSYSTEM <>", value, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMGreaterThan(String value) {
            addCriterion("SUBSYSTEM >", value, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMGreaterThanOrEqualTo(String value) {
            addCriterion("SUBSYSTEM >=", value, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMLessThan(String value) {
            addCriterion("SUBSYSTEM <", value, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMLessThanOrEqualTo(String value) {
            addCriterion("SUBSYSTEM <=", value, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMLike(String value) {
            addCriterion("SUBSYSTEM like", value, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMNotLike(String value) {
            addCriterion("SUBSYSTEM not like", value, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMIn(List<String> values) {
            addCriterion("SUBSYSTEM in", values, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMNotIn(List<String> values) {
            addCriterion("SUBSYSTEM not in", values, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMBetween(String value1, String value2) {
            addCriterion("SUBSYSTEM between", value1, value2, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andSUBSYSTEMNotBetween(String value1, String value2) {
            addCriterion("SUBSYSTEM not between", value1, value2, "SUBSYSTEM");
            return (Criteria) this;
        }

        public Criteria andCOUNTIsNull() {
            addCriterion("COUNT is null");
            return (Criteria) this;
        }

        public Criteria andCOUNTIsNotNull() {
            addCriterion("COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andCOUNTEqualTo(Long value) {
            addCriterion("COUNT =", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTNotEqualTo(Long value) {
            addCriterion("COUNT <>", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTGreaterThan(Long value) {
            addCriterion("COUNT >", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTGreaterThanOrEqualTo(Long value) {
            addCriterion("COUNT >=", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTLessThan(Long value) {
            addCriterion("COUNT <", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTLessThanOrEqualTo(Long value) {
            addCriterion("COUNT <=", value, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTIn(List<Long> values) {
            addCriterion("COUNT in", values, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTNotIn(List<Long> values) {
            addCriterion("COUNT not in", values, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTBetween(Long value1, Long value2) {
            addCriterion("COUNT between", value1, value2, "COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNTNotBetween(Long value1, Long value2) {
            addCriterion("COUNT not between", value1, value2, "COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTIsNull() {
            addCriterion("MAX_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTIsNotNull() {
            addCriterion("MAX_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTEqualTo(Long value) {
            addCriterion("MAX_COUNT =", value, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTNotEqualTo(Long value) {
            addCriterion("MAX_COUNT <>", value, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTGreaterThan(Long value) {
            addCriterion("MAX_COUNT >", value, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTGreaterThanOrEqualTo(Long value) {
            addCriterion("MAX_COUNT >=", value, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTLessThan(Long value) {
            addCriterion("MAX_COUNT <", value, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTLessThanOrEqualTo(Long value) {
            addCriterion("MAX_COUNT <=", value, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTIn(List<Long> values) {
            addCriterion("MAX_COUNT in", values, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTNotIn(List<Long> values) {
            addCriterion("MAX_COUNT not in", values, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTBetween(Long value1, Long value2) {
            addCriterion("MAX_COUNT between", value1, value2, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNTNotBetween(Long value1, Long value2) {
            addCriterion("MAX_COUNT not between", value1, value2, "MAX_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTIsNull() {
            addCriterion("MIN_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTIsNotNull() {
            addCriterion("MIN_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTEqualTo(Long value) {
            addCriterion("MIN_COUNT =", value, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTNotEqualTo(Long value) {
            addCriterion("MIN_COUNT <>", value, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTGreaterThan(Long value) {
            addCriterion("MIN_COUNT >", value, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTGreaterThanOrEqualTo(Long value) {
            addCriterion("MIN_COUNT >=", value, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTLessThan(Long value) {
            addCriterion("MIN_COUNT <", value, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTLessThanOrEqualTo(Long value) {
            addCriterion("MIN_COUNT <=", value, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTIn(List<Long> values) {
            addCriterion("MIN_COUNT in", values, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTNotIn(List<Long> values) {
            addCriterion("MIN_COUNT not in", values, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTBetween(Long value1, Long value2) {
            addCriterion("MIN_COUNT between", value1, value2, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNTNotBetween(Long value1, Long value2) {
            addCriterion("MIN_COUNT not between", value1, value2, "MIN_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTIsNull() {
            addCriterion("AVG_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTIsNotNull() {
            addCriterion("AVG_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTEqualTo(Float value) {
            addCriterion("AVG_COUNT =", value, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTNotEqualTo(Float value) {
            addCriterion("AVG_COUNT <>", value, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTGreaterThan(Float value) {
            addCriterion("AVG_COUNT >", value, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTGreaterThanOrEqualTo(Float value) {
            addCriterion("AVG_COUNT >=", value, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTLessThan(Float value) {
            addCriterion("AVG_COUNT <", value, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTLessThanOrEqualTo(Float value) {
            addCriterion("AVG_COUNT <=", value, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTIn(List<Float> values) {
            addCriterion("AVG_COUNT in", values, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTNotIn(List<Float> values) {
            addCriterion("AVG_COUNT not in", values, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTBetween(Float value1, Float value2) {
            addCriterion("AVG_COUNT between", value1, value2, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNTNotBetween(Float value1, Float value2) {
            addCriterion("AVG_COUNT not between", value1, value2, "AVG_COUNT");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETIsNull() {
            addCriterion("COUNT_RESET is null");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETIsNotNull() {
            addCriterion("COUNT_RESET is not null");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETEqualTo(Long value) {
            addCriterion("COUNT_RESET =", value, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETNotEqualTo(Long value) {
            addCriterion("COUNT_RESET <>", value, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETGreaterThan(Long value) {
            addCriterion("COUNT_RESET >", value, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETGreaterThanOrEqualTo(Long value) {
            addCriterion("COUNT_RESET >=", value, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETLessThan(Long value) {
            addCriterion("COUNT_RESET <", value, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETLessThanOrEqualTo(Long value) {
            addCriterion("COUNT_RESET <=", value, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETIn(List<Long> values) {
            addCriterion("COUNT_RESET in", values, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETNotIn(List<Long> values) {
            addCriterion("COUNT_RESET not in", values, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETBetween(Long value1, Long value2) {
            addCriterion("COUNT_RESET between", value1, value2, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andCOUNT_RESETNotBetween(Long value1, Long value2) {
            addCriterion("COUNT_RESET not between", value1, value2, "COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETIsNull() {
            addCriterion("MAX_COUNT_RESET is null");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETIsNotNull() {
            addCriterion("MAX_COUNT_RESET is not null");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETEqualTo(Long value) {
            addCriterion("MAX_COUNT_RESET =", value, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETNotEqualTo(Long value) {
            addCriterion("MAX_COUNT_RESET <>", value, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETGreaterThan(Long value) {
            addCriterion("MAX_COUNT_RESET >", value, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETGreaterThanOrEqualTo(Long value) {
            addCriterion("MAX_COUNT_RESET >=", value, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETLessThan(Long value) {
            addCriterion("MAX_COUNT_RESET <", value, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETLessThanOrEqualTo(Long value) {
            addCriterion("MAX_COUNT_RESET <=", value, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETIn(List<Long> values) {
            addCriterion("MAX_COUNT_RESET in", values, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETNotIn(List<Long> values) {
            addCriterion("MAX_COUNT_RESET not in", values, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETBetween(Long value1, Long value2) {
            addCriterion("MAX_COUNT_RESET between", value1, value2, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMAX_COUNT_RESETNotBetween(Long value1, Long value2) {
            addCriterion("MAX_COUNT_RESET not between", value1, value2, "MAX_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETIsNull() {
            addCriterion("MIN_COUNT_RESET is null");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETIsNotNull() {
            addCriterion("MIN_COUNT_RESET is not null");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETEqualTo(Long value) {
            addCriterion("MIN_COUNT_RESET =", value, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETNotEqualTo(Long value) {
            addCriterion("MIN_COUNT_RESET <>", value, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETGreaterThan(Long value) {
            addCriterion("MIN_COUNT_RESET >", value, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETGreaterThanOrEqualTo(Long value) {
            addCriterion("MIN_COUNT_RESET >=", value, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETLessThan(Long value) {
            addCriterion("MIN_COUNT_RESET <", value, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETLessThanOrEqualTo(Long value) {
            addCriterion("MIN_COUNT_RESET <=", value, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETIn(List<Long> values) {
            addCriterion("MIN_COUNT_RESET in", values, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETNotIn(List<Long> values) {
            addCriterion("MIN_COUNT_RESET not in", values, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETBetween(Long value1, Long value2) {
            addCriterion("MIN_COUNT_RESET between", value1, value2, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andMIN_COUNT_RESETNotBetween(Long value1, Long value2) {
            addCriterion("MIN_COUNT_RESET not between", value1, value2, "MIN_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETIsNull() {
            addCriterion("AVG_COUNT_RESET is null");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETIsNotNull() {
            addCriterion("AVG_COUNT_RESET is not null");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETEqualTo(Float value) {
            addCriterion("AVG_COUNT_RESET =", value, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETNotEqualTo(Float value) {
            addCriterion("AVG_COUNT_RESET <>", value, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETGreaterThan(Float value) {
            addCriterion("AVG_COUNT_RESET >", value, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETGreaterThanOrEqualTo(Float value) {
            addCriterion("AVG_COUNT_RESET >=", value, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETLessThan(Float value) {
            addCriterion("AVG_COUNT_RESET <", value, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETLessThanOrEqualTo(Float value) {
            addCriterion("AVG_COUNT_RESET <=", value, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETIn(List<Float> values) {
            addCriterion("AVG_COUNT_RESET in", values, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETNotIn(List<Float> values) {
            addCriterion("AVG_COUNT_RESET not in", values, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETBetween(Float value1, Float value2) {
            addCriterion("AVG_COUNT_RESET between", value1, value2, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andAVG_COUNT_RESETNotBetween(Float value1, Float value2) {
            addCriterion("AVG_COUNT_RESET not between", value1, value2, "AVG_COUNT_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDIsNull() {
            addCriterion("TIME_ENABLED is null");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDIsNotNull() {
            addCriterion("TIME_ENABLED is not null");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDEqualTo(Date value) {
            addCriterion("TIME_ENABLED =", value, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDNotEqualTo(Date value) {
            addCriterion("TIME_ENABLED <>", value, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDGreaterThan(Date value) {
            addCriterion("TIME_ENABLED >", value, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDGreaterThanOrEqualTo(Date value) {
            addCriterion("TIME_ENABLED >=", value, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDLessThan(Date value) {
            addCriterion("TIME_ENABLED <", value, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDLessThanOrEqualTo(Date value) {
            addCriterion("TIME_ENABLED <=", value, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDIn(List<Date> values) {
            addCriterion("TIME_ENABLED in", values, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDNotIn(List<Date> values) {
            addCriterion("TIME_ENABLED not in", values, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDBetween(Date value1, Date value2) {
            addCriterion("TIME_ENABLED between", value1, value2, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ENABLEDNotBetween(Date value1, Date value2) {
            addCriterion("TIME_ENABLED not between", value1, value2, "TIME_ENABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDIsNull() {
            addCriterion("TIME_DISABLED is null");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDIsNotNull() {
            addCriterion("TIME_DISABLED is not null");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDEqualTo(Date value) {
            addCriterion("TIME_DISABLED =", value, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDNotEqualTo(Date value) {
            addCriterion("TIME_DISABLED <>", value, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDGreaterThan(Date value) {
            addCriterion("TIME_DISABLED >", value, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDGreaterThanOrEqualTo(Date value) {
            addCriterion("TIME_DISABLED >=", value, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDLessThan(Date value) {
            addCriterion("TIME_DISABLED <", value, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDLessThanOrEqualTo(Date value) {
            addCriterion("TIME_DISABLED <=", value, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDIn(List<Date> values) {
            addCriterion("TIME_DISABLED in", values, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDNotIn(List<Date> values) {
            addCriterion("TIME_DISABLED not in", values, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDBetween(Date value1, Date value2) {
            addCriterion("TIME_DISABLED between", value1, value2, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_DISABLEDNotBetween(Date value1, Date value2) {
            addCriterion("TIME_DISABLED not between", value1, value2, "TIME_DISABLED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDIsNull() {
            addCriterion("TIME_ELAPSED is null");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDIsNotNull() {
            addCriterion("TIME_ELAPSED is not null");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDEqualTo(Long value) {
            addCriterion("TIME_ELAPSED =", value, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDNotEqualTo(Long value) {
            addCriterion("TIME_ELAPSED <>", value, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDGreaterThan(Long value) {
            addCriterion("TIME_ELAPSED >", value, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDGreaterThanOrEqualTo(Long value) {
            addCriterion("TIME_ELAPSED >=", value, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDLessThan(Long value) {
            addCriterion("TIME_ELAPSED <", value, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDLessThanOrEqualTo(Long value) {
            addCriterion("TIME_ELAPSED <=", value, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDIn(List<Long> values) {
            addCriterion("TIME_ELAPSED in", values, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDNotIn(List<Long> values) {
            addCriterion("TIME_ELAPSED not in", values, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDBetween(Long value1, Long value2) {
            addCriterion("TIME_ELAPSED between", value1, value2, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_ELAPSEDNotBetween(Long value1, Long value2) {
            addCriterion("TIME_ELAPSED not between", value1, value2, "TIME_ELAPSED");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETIsNull() {
            addCriterion("TIME_RESET is null");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETIsNotNull() {
            addCriterion("TIME_RESET is not null");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETEqualTo(Date value) {
            addCriterion("TIME_RESET =", value, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETNotEqualTo(Date value) {
            addCriterion("TIME_RESET <>", value, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETGreaterThan(Date value) {
            addCriterion("TIME_RESET >", value, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETGreaterThanOrEqualTo(Date value) {
            addCriterion("TIME_RESET >=", value, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETLessThan(Date value) {
            addCriterion("TIME_RESET <", value, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETLessThanOrEqualTo(Date value) {
            addCriterion("TIME_RESET <=", value, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETIn(List<Date> values) {
            addCriterion("TIME_RESET in", values, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETNotIn(List<Date> values) {
            addCriterion("TIME_RESET not in", values, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETBetween(Date value1, Date value2) {
            addCriterion("TIME_RESET between", value1, value2, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andTIME_RESETNotBetween(Date value1, Date value2) {
            addCriterion("TIME_RESET not between", value1, value2, "TIME_RESET");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andSTATUSIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andSTATUSEqualTo(String value) {
            addCriterion("STATUS =", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThan(String value) {
            addCriterion("STATUS >", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThan(String value) {
            addCriterion("STATUS <", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSLike(String value) {
            addCriterion("STATUS like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotLike(String value) {
            addCriterion("STATUS not like", value, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSIn(List<String> values) {
            addCriterion("STATUS in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andSTATUSNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "STATUS");
            return (Criteria) this;
        }

        public Criteria andTYPEIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTYPEIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTYPEEqualTo(String value) {
            addCriterion("TYPE =", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotEqualTo(String value) {
            addCriterion("TYPE <>", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEGreaterThan(String value) {
            addCriterion("TYPE >", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEGreaterThanOrEqualTo(String value) {
            addCriterion("TYPE >=", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPELessThan(String value) {
            addCriterion("TYPE <", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPELessThanOrEqualTo(String value) {
            addCriterion("TYPE <=", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPELike(String value) {
            addCriterion("TYPE like", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotLike(String value) {
            addCriterion("TYPE not like", value, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEIn(List<String> values) {
            addCriterion("TYPE in", values, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotIn(List<String> values) {
            addCriterion("TYPE not in", values, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPEBetween(String value1, String value2) {
            addCriterion("TYPE between", value1, value2, "TYPE");
            return (Criteria) this;
        }

        public Criteria andTYPENotBetween(String value1, String value2) {
            addCriterion("TYPE not between", value1, value2, "TYPE");
            return (Criteria) this;
        }

        public Criteria andCOMMENTIsNull() {
            addCriterion("COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andCOMMENTIsNotNull() {
            addCriterion("COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCOMMENTEqualTo(String value) {
            addCriterion("COMMENT =", value, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTNotEqualTo(String value) {
            addCriterion("COMMENT <>", value, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTGreaterThan(String value) {
            addCriterion("COMMENT >", value, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTGreaterThanOrEqualTo(String value) {
            addCriterion("COMMENT >=", value, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTLessThan(String value) {
            addCriterion("COMMENT <", value, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTLessThanOrEqualTo(String value) {
            addCriterion("COMMENT <=", value, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTLike(String value) {
            addCriterion("COMMENT like", value, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTNotLike(String value) {
            addCriterion("COMMENT not like", value, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTIn(List<String> values) {
            addCriterion("COMMENT in", values, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTNotIn(List<String> values) {
            addCriterion("COMMENT not in", values, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTBetween(String value1, String value2) {
            addCriterion("COMMENT between", value1, value2, "COMMENT");
            return (Criteria) this;
        }

        public Criteria andCOMMENTNotBetween(String value1, String value2) {
            addCriterion("COMMENT not between", value1, value2, "COMMENT");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INNODB_METRICS
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}