package com.entity;

import java.util.ArrayList;
import java.util.List;

public class InnodbFtIndexCacheExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public InnodbFtIndexCacheExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWORDIsNull() {
            addCriterion("WORD is null");
            return (Criteria) this;
        }

        public Criteria andWORDIsNotNull() {
            addCriterion("WORD is not null");
            return (Criteria) this;
        }

        public Criteria andWORDEqualTo(String value) {
            addCriterion("WORD =", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDNotEqualTo(String value) {
            addCriterion("WORD <>", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDGreaterThan(String value) {
            addCriterion("WORD >", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDGreaterThanOrEqualTo(String value) {
            addCriterion("WORD >=", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDLessThan(String value) {
            addCriterion("WORD <", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDLessThanOrEqualTo(String value) {
            addCriterion("WORD <=", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDLike(String value) {
            addCriterion("WORD like", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDNotLike(String value) {
            addCriterion("WORD not like", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDIn(List<String> values) {
            addCriterion("WORD in", values, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDNotIn(List<String> values) {
            addCriterion("WORD not in", values, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDBetween(String value1, String value2) {
            addCriterion("WORD between", value1, value2, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDNotBetween(String value1, String value2) {
            addCriterion("WORD not between", value1, value2, "WORD");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDIsNull() {
            addCriterion("FIRST_DOC_ID is null");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDIsNotNull() {
            addCriterion("FIRST_DOC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDEqualTo(Long value) {
            addCriterion("FIRST_DOC_ID =", value, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDNotEqualTo(Long value) {
            addCriterion("FIRST_DOC_ID <>", value, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDGreaterThan(Long value) {
            addCriterion("FIRST_DOC_ID >", value, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDGreaterThanOrEqualTo(Long value) {
            addCriterion("FIRST_DOC_ID >=", value, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDLessThan(Long value) {
            addCriterion("FIRST_DOC_ID <", value, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDLessThanOrEqualTo(Long value) {
            addCriterion("FIRST_DOC_ID <=", value, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDIn(List<Long> values) {
            addCriterion("FIRST_DOC_ID in", values, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDNotIn(List<Long> values) {
            addCriterion("FIRST_DOC_ID not in", values, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDBetween(Long value1, Long value2) {
            addCriterion("FIRST_DOC_ID between", value1, value2, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andFIRST_DOC_IDNotBetween(Long value1, Long value2) {
            addCriterion("FIRST_DOC_ID not between", value1, value2, "FIRST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDIsNull() {
            addCriterion("LAST_DOC_ID is null");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDIsNotNull() {
            addCriterion("LAST_DOC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDEqualTo(Long value) {
            addCriterion("LAST_DOC_ID =", value, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDNotEqualTo(Long value) {
            addCriterion("LAST_DOC_ID <>", value, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDGreaterThan(Long value) {
            addCriterion("LAST_DOC_ID >", value, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDGreaterThanOrEqualTo(Long value) {
            addCriterion("LAST_DOC_ID >=", value, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDLessThan(Long value) {
            addCriterion("LAST_DOC_ID <", value, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDLessThanOrEqualTo(Long value) {
            addCriterion("LAST_DOC_ID <=", value, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDIn(List<Long> values) {
            addCriterion("LAST_DOC_ID in", values, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDNotIn(List<Long> values) {
            addCriterion("LAST_DOC_ID not in", values, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDBetween(Long value1, Long value2) {
            addCriterion("LAST_DOC_ID between", value1, value2, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andLAST_DOC_IDNotBetween(Long value1, Long value2) {
            addCriterion("LAST_DOC_ID not between", value1, value2, "LAST_DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTIsNull() {
            addCriterion("DOC_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTIsNotNull() {
            addCriterion("DOC_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTEqualTo(Long value) {
            addCriterion("DOC_COUNT =", value, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTNotEqualTo(Long value) {
            addCriterion("DOC_COUNT <>", value, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTGreaterThan(Long value) {
            addCriterion("DOC_COUNT >", value, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTGreaterThanOrEqualTo(Long value) {
            addCriterion("DOC_COUNT >=", value, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTLessThan(Long value) {
            addCriterion("DOC_COUNT <", value, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTLessThanOrEqualTo(Long value) {
            addCriterion("DOC_COUNT <=", value, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTIn(List<Long> values) {
            addCriterion("DOC_COUNT in", values, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTNotIn(List<Long> values) {
            addCriterion("DOC_COUNT not in", values, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTBetween(Long value1, Long value2) {
            addCriterion("DOC_COUNT between", value1, value2, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_COUNTNotBetween(Long value1, Long value2) {
            addCriterion("DOC_COUNT not between", value1, value2, "DOC_COUNT");
            return (Criteria) this;
        }

        public Criteria andDOC_IDIsNull() {
            addCriterion("DOC_ID is null");
            return (Criteria) this;
        }

        public Criteria andDOC_IDIsNotNull() {
            addCriterion("DOC_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDOC_IDEqualTo(Long value) {
            addCriterion("DOC_ID =", value, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_IDNotEqualTo(Long value) {
            addCriterion("DOC_ID <>", value, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_IDGreaterThan(Long value) {
            addCriterion("DOC_ID >", value, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_IDGreaterThanOrEqualTo(Long value) {
            addCriterion("DOC_ID >=", value, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_IDLessThan(Long value) {
            addCriterion("DOC_ID <", value, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_IDLessThanOrEqualTo(Long value) {
            addCriterion("DOC_ID <=", value, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_IDIn(List<Long> values) {
            addCriterion("DOC_ID in", values, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_IDNotIn(List<Long> values) {
            addCriterion("DOC_ID not in", values, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_IDBetween(Long value1, Long value2) {
            addCriterion("DOC_ID between", value1, value2, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andDOC_IDNotBetween(Long value1, Long value2) {
            addCriterion("DOC_ID not between", value1, value2, "DOC_ID");
            return (Criteria) this;
        }

        public Criteria andPOSITIONIsNull() {
            addCriterion("POSITION is null");
            return (Criteria) this;
        }

        public Criteria andPOSITIONIsNotNull() {
            addCriterion("POSITION is not null");
            return (Criteria) this;
        }

        public Criteria andPOSITIONEqualTo(Long value) {
            addCriterion("POSITION =", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONNotEqualTo(Long value) {
            addCriterion("POSITION <>", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONGreaterThan(Long value) {
            addCriterion("POSITION >", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONGreaterThanOrEqualTo(Long value) {
            addCriterion("POSITION >=", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONLessThan(Long value) {
            addCriterion("POSITION <", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONLessThanOrEqualTo(Long value) {
            addCriterion("POSITION <=", value, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONIn(List<Long> values) {
            addCriterion("POSITION in", values, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONNotIn(List<Long> values) {
            addCriterion("POSITION not in", values, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONBetween(Long value1, Long value2) {
            addCriterion("POSITION between", value1, value2, "POSITION");
            return (Criteria) this;
        }

        public Criteria andPOSITIONNotBetween(Long value1, Long value2) {
            addCriterion("POSITION not between", value1, value2, "POSITION");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table INNODB_FT_INDEX_CACHE
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}