package com.entity;

public class InnodbFtBeingDeleted {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column INNODB_FT_BEING_DELETED.DOC_ID
     *
     * @mbg.generated
     */
    private Long DOC_ID;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column INNODB_FT_BEING_DELETED.DOC_ID
     *
     * @return the value of INNODB_FT_BEING_DELETED.DOC_ID
     *
     * @mbg.generated
     */
    public Long getDOC_ID() {
        return DOC_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column INNODB_FT_BEING_DELETED.DOC_ID
     *
     * @param DOC_ID the value for INNODB_FT_BEING_DELETED.DOC_ID
     *
     * @mbg.generated
     */
    public void setDOC_ID(Long DOC_ID) {
        this.DOC_ID = DOC_ID;
    }
}