package com.entity;

import java.util.ArrayList;
import java.util.List;

public class KeywordsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public KeywordsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWORDIsNull() {
            addCriterion("WORD is null");
            return (Criteria) this;
        }

        public Criteria andWORDIsNotNull() {
            addCriterion("WORD is not null");
            return (Criteria) this;
        }

        public Criteria andWORDEqualTo(String value) {
            addCriterion("WORD =", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDNotEqualTo(String value) {
            addCriterion("WORD <>", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDGreaterThan(String value) {
            addCriterion("WORD >", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDGreaterThanOrEqualTo(String value) {
            addCriterion("WORD >=", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDLessThan(String value) {
            addCriterion("WORD <", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDLessThanOrEqualTo(String value) {
            addCriterion("WORD <=", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDLike(String value) {
            addCriterion("WORD like", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDNotLike(String value) {
            addCriterion("WORD not like", value, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDIn(List<String> values) {
            addCriterion("WORD in", values, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDNotIn(List<String> values) {
            addCriterion("WORD not in", values, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDBetween(String value1, String value2) {
            addCriterion("WORD between", value1, value2, "WORD");
            return (Criteria) this;
        }

        public Criteria andWORDNotBetween(String value1, String value2) {
            addCriterion("WORD not between", value1, value2, "WORD");
            return (Criteria) this;
        }

        public Criteria andRESERVEDIsNull() {
            addCriterion("RESERVED is null");
            return (Criteria) this;
        }

        public Criteria andRESERVEDIsNotNull() {
            addCriterion("RESERVED is not null");
            return (Criteria) this;
        }

        public Criteria andRESERVEDEqualTo(Integer value) {
            addCriterion("RESERVED =", value, "RESERVED");
            return (Criteria) this;
        }

        public Criteria andRESERVEDNotEqualTo(Integer value) {
            addCriterion("RESERVED <>", value, "RESERVED");
            return (Criteria) this;
        }

        public Criteria andRESERVEDGreaterThan(Integer value) {
            addCriterion("RESERVED >", value, "RESERVED");
            return (Criteria) this;
        }

        public Criteria andRESERVEDGreaterThanOrEqualTo(Integer value) {
            addCriterion("RESERVED >=", value, "RESERVED");
            return (Criteria) this;
        }

        public Criteria andRESERVEDLessThan(Integer value) {
            addCriterion("RESERVED <", value, "RESERVED");
            return (Criteria) this;
        }

        public Criteria andRESERVEDLessThanOrEqualTo(Integer value) {
            addCriterion("RESERVED <=", value, "RESERVED");
            return (Criteria) this;
        }

        public Criteria andRESERVEDIn(List<Integer> values) {
            addCriterion("RESERVED in", values, "RESERVED");
            return (Criteria) this;
        }

        public Criteria andRESERVEDNotIn(List<Integer> values) {
            addCriterion("RESERVED not in", values, "RESERVED");
            return (Criteria) this;
        }

        public Criteria andRESERVEDBetween(Integer value1, Integer value2) {
            addCriterion("RESERVED between", value1, value2, "RESERVED");
            return (Criteria) this;
        }

        public Criteria andRESERVEDNotBetween(Integer value1, Integer value2) {
            addCriterion("RESERVED not between", value1, value2, "RESERVED");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KEYWORDS
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table KEYWORDS
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}