package com.entity;

public class Plugins {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_NAME
     *
     * @mbg.generated
     */
    private String PLUGIN_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_VERSION
     *
     * @mbg.generated
     */
    private String PLUGIN_VERSION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_STATUS
     *
     * @mbg.generated
     */
    private String PLUGIN_STATUS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_TYPE
     *
     * @mbg.generated
     */
    private String PLUGIN_TYPE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_TYPE_VERSION
     *
     * @mbg.generated
     */
    private String PLUGIN_TYPE_VERSION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_LIBRARY
     *
     * @mbg.generated
     */
    private String PLUGIN_LIBRARY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_LIBRARY_VERSION
     *
     * @mbg.generated
     */
    private String PLUGIN_LIBRARY_VERSION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_AUTHOR
     *
     * @mbg.generated
     */
    private String PLUGIN_AUTHOR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_DESCRIPTION
     *
     * @mbg.generated
     */
    private String PLUGIN_DESCRIPTION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.PLUGIN_LICENSE
     *
     * @mbg.generated
     */
    private String PLUGIN_LICENSE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PLUGINS.LOAD_OPTION
     *
     * @mbg.generated
     */
    private String LOAD_OPTION;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_NAME
     *
     * @return the value of PLUGINS.PLUGIN_NAME
     *
     * @mbg.generated
     */
    public String getPLUGIN_NAME() {
        return PLUGIN_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_NAME
     *
     * @param PLUGIN_NAME the value for PLUGINS.PLUGIN_NAME
     *
     * @mbg.generated
     */
    public void setPLUGIN_NAME(String PLUGIN_NAME) {
        this.PLUGIN_NAME = PLUGIN_NAME == null ? null : PLUGIN_NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_VERSION
     *
     * @return the value of PLUGINS.PLUGIN_VERSION
     *
     * @mbg.generated
     */
    public String getPLUGIN_VERSION() {
        return PLUGIN_VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_VERSION
     *
     * @param PLUGIN_VERSION the value for PLUGINS.PLUGIN_VERSION
     *
     * @mbg.generated
     */
    public void setPLUGIN_VERSION(String PLUGIN_VERSION) {
        this.PLUGIN_VERSION = PLUGIN_VERSION == null ? null : PLUGIN_VERSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_STATUS
     *
     * @return the value of PLUGINS.PLUGIN_STATUS
     *
     * @mbg.generated
     */
    public String getPLUGIN_STATUS() {
        return PLUGIN_STATUS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_STATUS
     *
     * @param PLUGIN_STATUS the value for PLUGINS.PLUGIN_STATUS
     *
     * @mbg.generated
     */
    public void setPLUGIN_STATUS(String PLUGIN_STATUS) {
        this.PLUGIN_STATUS = PLUGIN_STATUS == null ? null : PLUGIN_STATUS.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_TYPE
     *
     * @return the value of PLUGINS.PLUGIN_TYPE
     *
     * @mbg.generated
     */
    public String getPLUGIN_TYPE() {
        return PLUGIN_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_TYPE
     *
     * @param PLUGIN_TYPE the value for PLUGINS.PLUGIN_TYPE
     *
     * @mbg.generated
     */
    public void setPLUGIN_TYPE(String PLUGIN_TYPE) {
        this.PLUGIN_TYPE = PLUGIN_TYPE == null ? null : PLUGIN_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_TYPE_VERSION
     *
     * @return the value of PLUGINS.PLUGIN_TYPE_VERSION
     *
     * @mbg.generated
     */
    public String getPLUGIN_TYPE_VERSION() {
        return PLUGIN_TYPE_VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_TYPE_VERSION
     *
     * @param PLUGIN_TYPE_VERSION the value for PLUGINS.PLUGIN_TYPE_VERSION
     *
     * @mbg.generated
     */
    public void setPLUGIN_TYPE_VERSION(String PLUGIN_TYPE_VERSION) {
        this.PLUGIN_TYPE_VERSION = PLUGIN_TYPE_VERSION == null ? null : PLUGIN_TYPE_VERSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_LIBRARY
     *
     * @return the value of PLUGINS.PLUGIN_LIBRARY
     *
     * @mbg.generated
     */
    public String getPLUGIN_LIBRARY() {
        return PLUGIN_LIBRARY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_LIBRARY
     *
     * @param PLUGIN_LIBRARY the value for PLUGINS.PLUGIN_LIBRARY
     *
     * @mbg.generated
     */
    public void setPLUGIN_LIBRARY(String PLUGIN_LIBRARY) {
        this.PLUGIN_LIBRARY = PLUGIN_LIBRARY == null ? null : PLUGIN_LIBRARY.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_LIBRARY_VERSION
     *
     * @return the value of PLUGINS.PLUGIN_LIBRARY_VERSION
     *
     * @mbg.generated
     */
    public String getPLUGIN_LIBRARY_VERSION() {
        return PLUGIN_LIBRARY_VERSION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_LIBRARY_VERSION
     *
     * @param PLUGIN_LIBRARY_VERSION the value for PLUGINS.PLUGIN_LIBRARY_VERSION
     *
     * @mbg.generated
     */
    public void setPLUGIN_LIBRARY_VERSION(String PLUGIN_LIBRARY_VERSION) {
        this.PLUGIN_LIBRARY_VERSION = PLUGIN_LIBRARY_VERSION == null ? null : PLUGIN_LIBRARY_VERSION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_AUTHOR
     *
     * @return the value of PLUGINS.PLUGIN_AUTHOR
     *
     * @mbg.generated
     */
    public String getPLUGIN_AUTHOR() {
        return PLUGIN_AUTHOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_AUTHOR
     *
     * @param PLUGIN_AUTHOR the value for PLUGINS.PLUGIN_AUTHOR
     *
     * @mbg.generated
     */
    public void setPLUGIN_AUTHOR(String PLUGIN_AUTHOR) {
        this.PLUGIN_AUTHOR = PLUGIN_AUTHOR == null ? null : PLUGIN_AUTHOR.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_DESCRIPTION
     *
     * @return the value of PLUGINS.PLUGIN_DESCRIPTION
     *
     * @mbg.generated
     */
    public String getPLUGIN_DESCRIPTION() {
        return PLUGIN_DESCRIPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_DESCRIPTION
     *
     * @param PLUGIN_DESCRIPTION the value for PLUGINS.PLUGIN_DESCRIPTION
     *
     * @mbg.generated
     */
    public void setPLUGIN_DESCRIPTION(String PLUGIN_DESCRIPTION) {
        this.PLUGIN_DESCRIPTION = PLUGIN_DESCRIPTION == null ? null : PLUGIN_DESCRIPTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.PLUGIN_LICENSE
     *
     * @return the value of PLUGINS.PLUGIN_LICENSE
     *
     * @mbg.generated
     */
    public String getPLUGIN_LICENSE() {
        return PLUGIN_LICENSE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.PLUGIN_LICENSE
     *
     * @param PLUGIN_LICENSE the value for PLUGINS.PLUGIN_LICENSE
     *
     * @mbg.generated
     */
    public void setPLUGIN_LICENSE(String PLUGIN_LICENSE) {
        this.PLUGIN_LICENSE = PLUGIN_LICENSE == null ? null : PLUGIN_LICENSE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PLUGINS.LOAD_OPTION
     *
     * @return the value of PLUGINS.LOAD_OPTION
     *
     * @mbg.generated
     */
    public String getLOAD_OPTION() {
        return LOAD_OPTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PLUGINS.LOAD_OPTION
     *
     * @param LOAD_OPTION the value for PLUGINS.LOAD_OPTION
     *
     * @mbg.generated
     */
    public void setLOAD_OPTION(String LOAD_OPTION) {
        this.LOAD_OPTION = LOAD_OPTION == null ? null : LOAD_OPTION.trim();
    }
}