package com.entity;

public class Profiling {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.QUERY_ID
     *
     * @mbg.generated
     */
    private Integer QUERY_ID;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.SEQ
     *
     * @mbg.generated
     */
    private Integer SEQ;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.STATE
     *
     * @mbg.generated
     */
    private String STATE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.DURATION
     *
     * @mbg.generated
     */
    private Short DURATION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.CPU_USER
     *
     * @mbg.generated
     */
    private Short CPU_USER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.CPU_SYSTEM
     *
     * @mbg.generated
     */
    private Short CPU_SYSTEM;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.CONTEXT_VOLUNTARY
     *
     * @mbg.generated
     */
    private Integer CONTEXT_VOLUNTARY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.CONTEXT_INVOLUNTARY
     *
     * @mbg.generated
     */
    private Integer CONTEXT_INVOLUNTARY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.BLOCK_OPS_IN
     *
     * @mbg.generated
     */
    private Integer BLOCK_OPS_IN;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.BLOCK_OPS_OUT
     *
     * @mbg.generated
     */
    private Integer BLOCK_OPS_OUT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.MESSAGES_SENT
     *
     * @mbg.generated
     */
    private Integer MESSAGES_SENT;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.MESSAGES_RECEIVED
     *
     * @mbg.generated
     */
    private Integer MESSAGES_RECEIVED;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.PAGE_FAULTS_MAJOR
     *
     * @mbg.generated
     */
    private Integer PAGE_FAULTS_MAJOR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.PAGE_FAULTS_MINOR
     *
     * @mbg.generated
     */
    private Integer PAGE_FAULTS_MINOR;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.SWAPS
     *
     * @mbg.generated
     */
    private Integer SWAPS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.SOURCE_FUNCTION
     *
     * @mbg.generated
     */
    private String SOURCE_FUNCTION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.SOURCE_FILE
     *
     * @mbg.generated
     */
    private String SOURCE_FILE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PROFILING.SOURCE_LINE
     *
     * @mbg.generated
     */
    private Integer SOURCE_LINE;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.QUERY_ID
     *
     * @return the value of PROFILING.QUERY_ID
     *
     * @mbg.generated
     */
    public Integer getQUERY_ID() {
        return QUERY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.QUERY_ID
     *
     * @param QUERY_ID the value for PROFILING.QUERY_ID
     *
     * @mbg.generated
     */
    public void setQUERY_ID(Integer QUERY_ID) {
        this.QUERY_ID = QUERY_ID;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.SEQ
     *
     * @return the value of PROFILING.SEQ
     *
     * @mbg.generated
     */
    public Integer getSEQ() {
        return SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.SEQ
     *
     * @param SEQ the value for PROFILING.SEQ
     *
     * @mbg.generated
     */
    public void setSEQ(Integer SEQ) {
        this.SEQ = SEQ;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.STATE
     *
     * @return the value of PROFILING.STATE
     *
     * @mbg.generated
     */
    public String getSTATE() {
        return STATE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.STATE
     *
     * @param STATE the value for PROFILING.STATE
     *
     * @mbg.generated
     */
    public void setSTATE(String STATE) {
        this.STATE = STATE == null ? null : STATE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.DURATION
     *
     * @return the value of PROFILING.DURATION
     *
     * @mbg.generated
     */
    public Short getDURATION() {
        return DURATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.DURATION
     *
     * @param DURATION the value for PROFILING.DURATION
     *
     * @mbg.generated
     */
    public void setDURATION(Short DURATION) {
        this.DURATION = DURATION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.CPU_USER
     *
     * @return the value of PROFILING.CPU_USER
     *
     * @mbg.generated
     */
    public Short getCPU_USER() {
        return CPU_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.CPU_USER
     *
     * @param CPU_USER the value for PROFILING.CPU_USER
     *
     * @mbg.generated
     */
    public void setCPU_USER(Short CPU_USER) {
        this.CPU_USER = CPU_USER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.CPU_SYSTEM
     *
     * @return the value of PROFILING.CPU_SYSTEM
     *
     * @mbg.generated
     */
    public Short getCPU_SYSTEM() {
        return CPU_SYSTEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.CPU_SYSTEM
     *
     * @param CPU_SYSTEM the value for PROFILING.CPU_SYSTEM
     *
     * @mbg.generated
     */
    public void setCPU_SYSTEM(Short CPU_SYSTEM) {
        this.CPU_SYSTEM = CPU_SYSTEM;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.CONTEXT_VOLUNTARY
     *
     * @return the value of PROFILING.CONTEXT_VOLUNTARY
     *
     * @mbg.generated
     */
    public Integer getCONTEXT_VOLUNTARY() {
        return CONTEXT_VOLUNTARY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.CONTEXT_VOLUNTARY
     *
     * @param CONTEXT_VOLUNTARY the value for PROFILING.CONTEXT_VOLUNTARY
     *
     * @mbg.generated
     */
    public void setCONTEXT_VOLUNTARY(Integer CONTEXT_VOLUNTARY) {
        this.CONTEXT_VOLUNTARY = CONTEXT_VOLUNTARY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.CONTEXT_INVOLUNTARY
     *
     * @return the value of PROFILING.CONTEXT_INVOLUNTARY
     *
     * @mbg.generated
     */
    public Integer getCONTEXT_INVOLUNTARY() {
        return CONTEXT_INVOLUNTARY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.CONTEXT_INVOLUNTARY
     *
     * @param CONTEXT_INVOLUNTARY the value for PROFILING.CONTEXT_INVOLUNTARY
     *
     * @mbg.generated
     */
    public void setCONTEXT_INVOLUNTARY(Integer CONTEXT_INVOLUNTARY) {
        this.CONTEXT_INVOLUNTARY = CONTEXT_INVOLUNTARY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.BLOCK_OPS_IN
     *
     * @return the value of PROFILING.BLOCK_OPS_IN
     *
     * @mbg.generated
     */
    public Integer getBLOCK_OPS_IN() {
        return BLOCK_OPS_IN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.BLOCK_OPS_IN
     *
     * @param BLOCK_OPS_IN the value for PROFILING.BLOCK_OPS_IN
     *
     * @mbg.generated
     */
    public void setBLOCK_OPS_IN(Integer BLOCK_OPS_IN) {
        this.BLOCK_OPS_IN = BLOCK_OPS_IN;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.BLOCK_OPS_OUT
     *
     * @return the value of PROFILING.BLOCK_OPS_OUT
     *
     * @mbg.generated
     */
    public Integer getBLOCK_OPS_OUT() {
        return BLOCK_OPS_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.BLOCK_OPS_OUT
     *
     * @param BLOCK_OPS_OUT the value for PROFILING.BLOCK_OPS_OUT
     *
     * @mbg.generated
     */
    public void setBLOCK_OPS_OUT(Integer BLOCK_OPS_OUT) {
        this.BLOCK_OPS_OUT = BLOCK_OPS_OUT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.MESSAGES_SENT
     *
     * @return the value of PROFILING.MESSAGES_SENT
     *
     * @mbg.generated
     */
    public Integer getMESSAGES_SENT() {
        return MESSAGES_SENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.MESSAGES_SENT
     *
     * @param MESSAGES_SENT the value for PROFILING.MESSAGES_SENT
     *
     * @mbg.generated
     */
    public void setMESSAGES_SENT(Integer MESSAGES_SENT) {
        this.MESSAGES_SENT = MESSAGES_SENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.MESSAGES_RECEIVED
     *
     * @return the value of PROFILING.MESSAGES_RECEIVED
     *
     * @mbg.generated
     */
    public Integer getMESSAGES_RECEIVED() {
        return MESSAGES_RECEIVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.MESSAGES_RECEIVED
     *
     * @param MESSAGES_RECEIVED the value for PROFILING.MESSAGES_RECEIVED
     *
     * @mbg.generated
     */
    public void setMESSAGES_RECEIVED(Integer MESSAGES_RECEIVED) {
        this.MESSAGES_RECEIVED = MESSAGES_RECEIVED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.PAGE_FAULTS_MAJOR
     *
     * @return the value of PROFILING.PAGE_FAULTS_MAJOR
     *
     * @mbg.generated
     */
    public Integer getPAGE_FAULTS_MAJOR() {
        return PAGE_FAULTS_MAJOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.PAGE_FAULTS_MAJOR
     *
     * @param PAGE_FAULTS_MAJOR the value for PROFILING.PAGE_FAULTS_MAJOR
     *
     * @mbg.generated
     */
    public void setPAGE_FAULTS_MAJOR(Integer PAGE_FAULTS_MAJOR) {
        this.PAGE_FAULTS_MAJOR = PAGE_FAULTS_MAJOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.PAGE_FAULTS_MINOR
     *
     * @return the value of PROFILING.PAGE_FAULTS_MINOR
     *
     * @mbg.generated
     */
    public Integer getPAGE_FAULTS_MINOR() {
        return PAGE_FAULTS_MINOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.PAGE_FAULTS_MINOR
     *
     * @param PAGE_FAULTS_MINOR the value for PROFILING.PAGE_FAULTS_MINOR
     *
     * @mbg.generated
     */
    public void setPAGE_FAULTS_MINOR(Integer PAGE_FAULTS_MINOR) {
        this.PAGE_FAULTS_MINOR = PAGE_FAULTS_MINOR;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.SWAPS
     *
     * @return the value of PROFILING.SWAPS
     *
     * @mbg.generated
     */
    public Integer getSWAPS() {
        return SWAPS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.SWAPS
     *
     * @param SWAPS the value for PROFILING.SWAPS
     *
     * @mbg.generated
     */
    public void setSWAPS(Integer SWAPS) {
        this.SWAPS = SWAPS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.SOURCE_FUNCTION
     *
     * @return the value of PROFILING.SOURCE_FUNCTION
     *
     * @mbg.generated
     */
    public String getSOURCE_FUNCTION() {
        return SOURCE_FUNCTION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.SOURCE_FUNCTION
     *
     * @param SOURCE_FUNCTION the value for PROFILING.SOURCE_FUNCTION
     *
     * @mbg.generated
     */
    public void setSOURCE_FUNCTION(String SOURCE_FUNCTION) {
        this.SOURCE_FUNCTION = SOURCE_FUNCTION == null ? null : SOURCE_FUNCTION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.SOURCE_FILE
     *
     * @return the value of PROFILING.SOURCE_FILE
     *
     * @mbg.generated
     */
    public String getSOURCE_FILE() {
        return SOURCE_FILE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.SOURCE_FILE
     *
     * @param SOURCE_FILE the value for PROFILING.SOURCE_FILE
     *
     * @mbg.generated
     */
    public void setSOURCE_FILE(String SOURCE_FILE) {
        this.SOURCE_FILE = SOURCE_FILE == null ? null : SOURCE_FILE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PROFILING.SOURCE_LINE
     *
     * @return the value of PROFILING.SOURCE_LINE
     *
     * @mbg.generated
     */
    public Integer getSOURCE_LINE() {
        return SOURCE_LINE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PROFILING.SOURCE_LINE
     *
     * @param SOURCE_LINE the value for PROFILING.SOURCE_LINE
     *
     * @mbg.generated
     */
    public void setSOURCE_LINE(Integer SOURCE_LINE) {
        this.SOURCE_LINE = SOURCE_LINE;
    }
}