package com.entity;

public class RoutinesWithBLOBs extends Routines {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROUTINES.DATA_TYPE
     *
     * @mbg.generated
     */
    private String DATA_TYPE;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROUTINES.DTD_IDENTIFIER
     *
     * @mbg.generated
     */
    private String DTD_IDENTIFIER;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROUTINES.ROUTINE_DEFINITION
     *
     * @mbg.generated
     */
    private String ROUTINE_DEFINITION;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROUTINES.EXTERNAL_NAME
     *
     * @mbg.generated
     */
    private byte[] EXTERNAL_NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROUTINES.SQL_PATH
     *
     * @mbg.generated
     */
    private byte[] SQL_PATH;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROUTINES.ROUTINE_COMMENT
     *
     * @mbg.generated
     */
    private String ROUTINE_COMMENT;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROUTINES.DATA_TYPE
     *
     * @return the value of ROUTINES.DATA_TYPE
     *
     * @mbg.generated
     */
    public String getDATA_TYPE() {
        return DATA_TYPE;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROUTINES.DATA_TYPE
     *
     * @param DATA_TYPE the value for ROUTINES.DATA_TYPE
     *
     * @mbg.generated
     */
    public void setDATA_TYPE(String DATA_TYPE) {
        this.DATA_TYPE = DATA_TYPE == null ? null : DATA_TYPE.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROUTINES.DTD_IDENTIFIER
     *
     * @return the value of ROUTINES.DTD_IDENTIFIER
     *
     * @mbg.generated
     */
    public String getDTD_IDENTIFIER() {
        return DTD_IDENTIFIER;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROUTINES.DTD_IDENTIFIER
     *
     * @param DTD_IDENTIFIER the value for ROUTINES.DTD_IDENTIFIER
     *
     * @mbg.generated
     */
    public void setDTD_IDENTIFIER(String DTD_IDENTIFIER) {
        this.DTD_IDENTIFIER = DTD_IDENTIFIER == null ? null : DTD_IDENTIFIER.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROUTINES.ROUTINE_DEFINITION
     *
     * @return the value of ROUTINES.ROUTINE_DEFINITION
     *
     * @mbg.generated
     */
    public String getROUTINE_DEFINITION() {
        return ROUTINE_DEFINITION;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROUTINES.ROUTINE_DEFINITION
     *
     * @param ROUTINE_DEFINITION the value for ROUTINES.ROUTINE_DEFINITION
     *
     * @mbg.generated
     */
    public void setROUTINE_DEFINITION(String ROUTINE_DEFINITION) {
        this.ROUTINE_DEFINITION = ROUTINE_DEFINITION == null ? null : ROUTINE_DEFINITION.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROUTINES.EXTERNAL_NAME
     *
     * @return the value of ROUTINES.EXTERNAL_NAME
     *
     * @mbg.generated
     */
    public byte[] getEXTERNAL_NAME() {
        return EXTERNAL_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROUTINES.EXTERNAL_NAME
     *
     * @param EXTERNAL_NAME the value for ROUTINES.EXTERNAL_NAME
     *
     * @mbg.generated
     */
    public void setEXTERNAL_NAME(byte[] EXTERNAL_NAME) {
        this.EXTERNAL_NAME = EXTERNAL_NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROUTINES.SQL_PATH
     *
     * @return the value of ROUTINES.SQL_PATH
     *
     * @mbg.generated
     */
    public byte[] getSQL_PATH() {
        return SQL_PATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROUTINES.SQL_PATH
     *
     * @param SQL_PATH the value for ROUTINES.SQL_PATH
     *
     * @mbg.generated
     */
    public void setSQL_PATH(byte[] SQL_PATH) {
        this.SQL_PATH = SQL_PATH;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROUTINES.ROUTINE_COMMENT
     *
     * @return the value of ROUTINES.ROUTINE_COMMENT
     *
     * @mbg.generated
     */
    public String getROUTINE_COMMENT() {
        return ROUTINE_COMMENT;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROUTINES.ROUTINE_COMMENT
     *
     * @param ROUTINE_COMMENT the value for ROUTINES.ROUTINE_COMMENT
     *
     * @mbg.generated
     */
    public void setROUTINE_COMMENT(String ROUTINE_COMMENT) {
        this.ROUTINE_COMMENT = ROUTINE_COMMENT == null ? null : ROUTINE_COMMENT.trim();
    }
}