package com.entity;

public class SetupConsumers {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setup_consumers.NAME
     *
     * @mbg.generated
     */
    private String NAME;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column setup_consumers.ENABLED
     *
     * @mbg.generated
     */
    private String ENABLED;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setup_consumers.NAME
     *
     * @return the value of setup_consumers.NAME
     *
     * @mbg.generated
     */
    public String getNAME() {
        return NAME;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setup_consumers.NAME
     *
     * @param NAME the value for setup_consumers.NAME
     *
     * @mbg.generated
     */
    public void setNAME(String NAME) {
        this.NAME = NAME == null ? null : NAME.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column setup_consumers.ENABLED
     *
     * @return the value of setup_consumers.ENABLED
     *
     * @mbg.generated
     */
    public String getENABLED() {
        return ENABLED;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column setup_consumers.ENABLED
     *
     * @param ENABLED the value for setup_consumers.ENABLED
     *
     * @mbg.generated
     */
    public void setENABLED(String ENABLED) {
        this.ENABLED = ENABLED == null ? null : ENABLED.trim();
    }
}