package com.entity;

public class SlaveWorkerInfoKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slave_worker_info.Channel_name
     *
     * @mbg.generated
     */
    private String channel_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column slave_worker_info.Id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slave_worker_info.Channel_name
     *
     * @return the value of slave_worker_info.Channel_name
     *
     * @mbg.generated
     */
    public String getChannel_name() {
        return channel_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slave_worker_info.Channel_name
     *
     * @param channel_name the value for slave_worker_info.Channel_name
     *
     * @mbg.generated
     */
    public void setChannel_name(String channel_name) {
        this.channel_name = channel_name == null ? null : channel_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column slave_worker_info.Id
     *
     * @return the value of slave_worker_info.Id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column slave_worker_info.Id
     *
     * @param id the value for slave_worker_info.Id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }
}