package com.entity;

import java.util.Date;

public class Temp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.district
     *
     * @mbg.generated
     */
    private String district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.field
     *
     * @mbg.generated
     */
    private String field;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.salary_min
     *
     * @mbg.generated
     */
    private Double salary_min;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.salary_max
     *
     * @mbg.generated
     */
    private Double salary_max;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.workyear
     *
     * @mbg.generated
     */
    private String workyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.education
     *
     * @mbg.generated
     */
    private String education;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.ptype
     *
     * @mbg.generated
     */
    private String ptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.pnature
     *
     * @mbg.generated
     */
    private String pnature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.advantage
     *
     * @mbg.generated
     */
    private String advantage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.published_at
     *
     * @mbg.generated
     */
    private Date published_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.updated_at
     *
     * @mbg.generated
     */
    private Date updated_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.company_id
     *
     * @mbg.generated
     */
    private Integer company_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp.region
     *
     * @mbg.generated
     */
    private Integer region;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pid
     *
     * @return the value of temp.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pid
     *
     * @param pid the value for temp.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.city
     *
     * @return the value of temp.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.city
     *
     * @param city the value for temp.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.district
     *
     * @return the value of temp.district
     *
     * @mbg.generated
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.district
     *
     * @param district the value for temp.district
     *
     * @mbg.generated
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.position
     *
     * @return the value of temp.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.position
     *
     * @param position the value for temp.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.field
     *
     * @return the value of temp.field
     *
     * @mbg.generated
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.field
     *
     * @param field the value for temp.field
     *
     * @mbg.generated
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.salary_min
     *
     * @return the value of temp.salary_min
     *
     * @mbg.generated
     */
    public Double getSalary_min() {
        return salary_min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.salary_min
     *
     * @param salary_min the value for temp.salary_min
     *
     * @mbg.generated
     */
    public void setSalary_min(Double salary_min) {
        this.salary_min = salary_min;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.salary_max
     *
     * @return the value of temp.salary_max
     *
     * @mbg.generated
     */
    public Double getSalary_max() {
        return salary_max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.salary_max
     *
     * @param salary_max the value for temp.salary_max
     *
     * @mbg.generated
     */
    public void setSalary_max(Double salary_max) {
        this.salary_max = salary_max;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.workyear
     *
     * @return the value of temp.workyear
     *
     * @mbg.generated
     */
    public String getWorkyear() {
        return workyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.workyear
     *
     * @param workyear the value for temp.workyear
     *
     * @mbg.generated
     */
    public void setWorkyear(String workyear) {
        this.workyear = workyear == null ? null : workyear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.education
     *
     * @return the value of temp.education
     *
     * @mbg.generated
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.education
     *
     * @param education the value for temp.education
     *
     * @mbg.generated
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.ptype
     *
     * @return the value of temp.ptype
     *
     * @mbg.generated
     */
    public String getPtype() {
        return ptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.ptype
     *
     * @param ptype the value for temp.ptype
     *
     * @mbg.generated
     */
    public void setPtype(String ptype) {
        this.ptype = ptype == null ? null : ptype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.pnature
     *
     * @return the value of temp.pnature
     *
     * @mbg.generated
     */
    public String getPnature() {
        return pnature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.pnature
     *
     * @param pnature the value for temp.pnature
     *
     * @mbg.generated
     */
    public void setPnature(String pnature) {
        this.pnature = pnature == null ? null : pnature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.advantage
     *
     * @return the value of temp.advantage
     *
     * @mbg.generated
     */
    public String getAdvantage() {
        return advantage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.advantage
     *
     * @param advantage the value for temp.advantage
     *
     * @mbg.generated
     */
    public void setAdvantage(String advantage) {
        this.advantage = advantage == null ? null : advantage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.published_at
     *
     * @return the value of temp.published_at
     *
     * @mbg.generated
     */
    public Date getPublished_at() {
        return published_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.published_at
     *
     * @param published_at the value for temp.published_at
     *
     * @mbg.generated
     */
    public void setPublished_at(Date published_at) {
        this.published_at = published_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.updated_at
     *
     * @return the value of temp.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdated_at() {
        return updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.updated_at
     *
     * @param updated_at the value for temp.updated_at
     *
     * @mbg.generated
     */
    public void setUpdated_at(Date updated_at) {
        this.updated_at = updated_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.company_id
     *
     * @return the value of temp.company_id
     *
     * @mbg.generated
     */
    public Integer getCompany_id() {
        return company_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.company_id
     *
     * @param company_id the value for temp.company_id
     *
     * @mbg.generated
     */
    public void setCompany_id(Integer company_id) {
        this.company_id = company_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp.region
     *
     * @return the value of temp.region
     *
     * @mbg.generated
     */
    public Integer getRegion() {
        return region;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp.region
     *
     * @param region the value for temp.region
     *
     * @mbg.generated
     */
    public void setRegion(Integer region) {
        this.region = region;
    }
}