package com.entity;

import java.util.ArrayList;
import java.util.List;

public class UserDefinedFunctionsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public UserDefinedFunctionsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUDF_NAMEIsNull() {
            addCriterion("UDF_NAME is null");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMEIsNotNull() {
            addCriterion("UDF_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMEEqualTo(String value) {
            addCriterion("UDF_NAME =", value, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMENotEqualTo(String value) {
            addCriterion("UDF_NAME <>", value, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMEGreaterThan(String value) {
            addCriterion("UDF_NAME >", value, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMEGreaterThanOrEqualTo(String value) {
            addCriterion("UDF_NAME >=", value, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMELessThan(String value) {
            addCriterion("UDF_NAME <", value, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMELessThanOrEqualTo(String value) {
            addCriterion("UDF_NAME <=", value, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMELike(String value) {
            addCriterion("UDF_NAME like", value, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMENotLike(String value) {
            addCriterion("UDF_NAME not like", value, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMEIn(List<String> values) {
            addCriterion("UDF_NAME in", values, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMENotIn(List<String> values) {
            addCriterion("UDF_NAME not in", values, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMEBetween(String value1, String value2) {
            addCriterion("UDF_NAME between", value1, value2, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_NAMENotBetween(String value1, String value2) {
            addCriterion("UDF_NAME not between", value1, value2, "UDF_NAME");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPEIsNull() {
            addCriterion("UDF_RETURN_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPEIsNotNull() {
            addCriterion("UDF_RETURN_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPEEqualTo(String value) {
            addCriterion("UDF_RETURN_TYPE =", value, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPENotEqualTo(String value) {
            addCriterion("UDF_RETURN_TYPE <>", value, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPEGreaterThan(String value) {
            addCriterion("UDF_RETURN_TYPE >", value, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("UDF_RETURN_TYPE >=", value, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPELessThan(String value) {
            addCriterion("UDF_RETURN_TYPE <", value, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPELessThanOrEqualTo(String value) {
            addCriterion("UDF_RETURN_TYPE <=", value, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPELike(String value) {
            addCriterion("UDF_RETURN_TYPE like", value, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPENotLike(String value) {
            addCriterion("UDF_RETURN_TYPE not like", value, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPEIn(List<String> values) {
            addCriterion("UDF_RETURN_TYPE in", values, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPENotIn(List<String> values) {
            addCriterion("UDF_RETURN_TYPE not in", values, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPEBetween(String value1, String value2) {
            addCriterion("UDF_RETURN_TYPE between", value1, value2, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_RETURN_TYPENotBetween(String value1, String value2) {
            addCriterion("UDF_RETURN_TYPE not between", value1, value2, "UDF_RETURN_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPEIsNull() {
            addCriterion("UDF_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPEIsNotNull() {
            addCriterion("UDF_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPEEqualTo(String value) {
            addCriterion("UDF_TYPE =", value, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPENotEqualTo(String value) {
            addCriterion("UDF_TYPE <>", value, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPEGreaterThan(String value) {
            addCriterion("UDF_TYPE >", value, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPEGreaterThanOrEqualTo(String value) {
            addCriterion("UDF_TYPE >=", value, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPELessThan(String value) {
            addCriterion("UDF_TYPE <", value, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPELessThanOrEqualTo(String value) {
            addCriterion("UDF_TYPE <=", value, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPELike(String value) {
            addCriterion("UDF_TYPE like", value, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPENotLike(String value) {
            addCriterion("UDF_TYPE not like", value, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPEIn(List<String> values) {
            addCriterion("UDF_TYPE in", values, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPENotIn(List<String> values) {
            addCriterion("UDF_TYPE not in", values, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPEBetween(String value1, String value2) {
            addCriterion("UDF_TYPE between", value1, value2, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_TYPENotBetween(String value1, String value2) {
            addCriterion("UDF_TYPE not between", value1, value2, "UDF_TYPE");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYIsNull() {
            addCriterion("UDF_LIBRARY is null");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYIsNotNull() {
            addCriterion("UDF_LIBRARY is not null");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYEqualTo(String value) {
            addCriterion("UDF_LIBRARY =", value, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYNotEqualTo(String value) {
            addCriterion("UDF_LIBRARY <>", value, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYGreaterThan(String value) {
            addCriterion("UDF_LIBRARY >", value, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYGreaterThanOrEqualTo(String value) {
            addCriterion("UDF_LIBRARY >=", value, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYLessThan(String value) {
            addCriterion("UDF_LIBRARY <", value, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYLessThanOrEqualTo(String value) {
            addCriterion("UDF_LIBRARY <=", value, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYLike(String value) {
            addCriterion("UDF_LIBRARY like", value, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYNotLike(String value) {
            addCriterion("UDF_LIBRARY not like", value, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYIn(List<String> values) {
            addCriterion("UDF_LIBRARY in", values, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYNotIn(List<String> values) {
            addCriterion("UDF_LIBRARY not in", values, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYBetween(String value1, String value2) {
            addCriterion("UDF_LIBRARY between", value1, value2, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_LIBRARYNotBetween(String value1, String value2) {
            addCriterion("UDF_LIBRARY not between", value1, value2, "UDF_LIBRARY");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTIsNull() {
            addCriterion("UDF_USAGE_COUNT is null");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTIsNotNull() {
            addCriterion("UDF_USAGE_COUNT is not null");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTEqualTo(Long value) {
            addCriterion("UDF_USAGE_COUNT =", value, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTNotEqualTo(Long value) {
            addCriterion("UDF_USAGE_COUNT <>", value, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTGreaterThan(Long value) {
            addCriterion("UDF_USAGE_COUNT >", value, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTGreaterThanOrEqualTo(Long value) {
            addCriterion("UDF_USAGE_COUNT >=", value, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTLessThan(Long value) {
            addCriterion("UDF_USAGE_COUNT <", value, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTLessThanOrEqualTo(Long value) {
            addCriterion("UDF_USAGE_COUNT <=", value, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTIn(List<Long> values) {
            addCriterion("UDF_USAGE_COUNT in", values, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTNotIn(List<Long> values) {
            addCriterion("UDF_USAGE_COUNT not in", values, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTBetween(Long value1, Long value2) {
            addCriterion("UDF_USAGE_COUNT between", value1, value2, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }

        public Criteria andUDF_USAGE_COUNTNotBetween(Long value1, Long value2) {
            addCriterion("UDF_USAGE_COUNT not between", value1, value2, "UDF_USAGE_COUNT");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_defined_functions
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_defined_functions
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}